@extends('layouts.dashboard')

@section('content')
<div class="page-heading">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h3 class="fw-bold text-dark mb-1">Company KPI Dashboard</h3>
            <p class="text-muted mb-0">Performance monitoring & Employee of the Month across company</p>
        </div>
        <div class="col-md-6 text-right">
            <div class="d-flex justify-content-end align-items-center flex-wrap gap-2">
                <form method="GET" class="form-inline d-flex align-items-center me-2">
                    <label class="me-2 fw-bold text-dark mb-0">Period: </label>
                    <input type="month" name="period" value="{{ $period }}" class="form-control" onchange="this.form.submit()">
                </form>

                @if($canGenerate ?? false)
                <button type="button" class="btn btn-primary btn-md shadow-sm" data-bs-toggle="modal" data-bs-target="#confirmRecalculateModal">
                    <i class="bi bi-play-circle-fill me-1"></i> {{ ($isGenerated ?? false) ? 'Recalculate KPI' : 'Generate KPI Periode Ini' }}
                </button>
                @endif
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container-fluid px-0">
        
        @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show border-0 shadow-sm mb-4" role="alert">
                <i class="bi bi-check-circle-fill me-2"></i> {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif

        @if(!($isGenerated ?? true))
            <!-- Empty State Card when KPI has not been generated by HR -->
            <div class="card border-0 shadow-sm my-4">
                <div class="card-body text-center py-5">
                    <div class="mb-3">
                        <i class="bi bi-calendar-x text-warning display-4"></i>
                    </div>
                    <h4 class="fw-bold text-dark">KPI Belum Digenerate untuk Periode {{ $periodFormatted }}</h4>
                    <p class="text-muted max-w-lg mx-auto mb-4">
                        Laporan KPI dan penentuan Employee of the Month pada periode ini belum diterbitkan oleh HR / Master Admin. <br>
                        Penilaian dihitung secara transparan dari <strong>50% Kepatuhan Checkout Presensi</strong> dan <strong>50% Pengisian Log Kerja Harian</strong>.
                    </p>
                    @if($canGenerate ?? false)
                        <button type="button" class="btn btn-primary btn-lg px-4 shadow" data-bs-toggle="modal" data-bs-target="#confirmRecalculateModal">
                            <i class="bi bi-play-circle-fill me-2"></i> Generate KPI Periode Ini Sekarang
                        </button>
                    @else
                        <span class="badge bg-secondary px-3 py-2 fs-6">Menunggu HR Administrator memproses KPI bulan ini</span>
                    @endif
                </div>
            </div>
        @else
        <!-- System Update Status -->
        <div class="row mb-4">
            <div class="col-12">
                <div class="alert alert-primary d-flex align-items-center justify-content-between border-0 shadow-sm">
                    <div>
                        <i class="bi bi-check-circle-fill me-2"></i>
                        <strong>Last Calculation:</strong> {{ $lastUpdated ? \Carbon\Carbon::parse($lastUpdated)->format('d M Y, H:i') : 'Up to Date' }}
                    </div>
                    <span class="badge bg-white text-primary px-3 py-2 border shadow-sm">
                        <i class="bi bi-layers-fill me-1"></i> Mode: 2 Indikator (Checkout + Log Kerja)
                    </span>
                </div>
            </div>
        </div>

<style>
    /* Aratech Luxury Hall-of-Fame Showcase Theme */
    .hall-of-fame-card {
        background: linear-gradient(135deg, #0f172a 0%, #1e3a8a 50%, #1e1b4b 100%);
        border-radius: 20px;
        border: 1px solid rgba(255, 255, 255, 0.15);
        box-shadow: 0 15px 35px rgba(30, 58, 138, 0.25);
        position: relative;
        overflow: hidden;
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
    .hall-of-fame-card:hover {
        transform: translateY(-4px);
        box-shadow: 0 20px 40px rgba(30, 58, 138, 0.35);
    }
    .hall-of-fame-card::before {
        content: '';
        position: absolute;
        top: -40%;
        right: -20%;
        width: 260px;
        height: 260px;
        background: radial-gradient(circle, rgba(245, 158, 11, 0.25) 0%, transparent 70%);
        border-radius: 50%;
        pointer-events: none;
    }
    .prestige-gold-badge {
        background: linear-gradient(90deg, #b45309 0%, #f59e0b 50%, #fbbf24 100%);
        color: #ffffff;
        font-weight: 800;
        letter-spacing: 1px;
        border-radius: 30px;
        box-shadow: 0 4px 15px rgba(245, 158, 11, 0.4);
        border: 1px solid rgba(255, 255, 255, 0.3);
    }
    .trophy-ring {
        width: 78px;
        height: 78px;
        border-radius: 50%;
        background: linear-gradient(135deg, rgba(254, 243, 199, 0.25) 0%, rgba(245, 158, 11, 0.35) 100%);
        border: 2px solid rgba(251, 191, 36, 0.6);
        display: inline-flex;
        align-items: center;
        justify-content: center;
        box-shadow: 0 0 25px rgba(245, 158, 11, 0.4);
    }
    .trophy-ring i {
        font-size: 2.8rem;
        color: #fbbf24;
        filter: drop-shadow(0 2px 8px rgba(0, 0, 0, 0.5));
    }
    .score-pill-gold {
        background: rgba(255, 255, 255, 0.12);
        backdrop-filter: blur(10px);
        border: 1px solid rgba(251, 191, 36, 0.4);
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    }
    .btn-prestige-gold {
        background: linear-gradient(90deg, #f59e0b 0%, #d97706 100%);
        color: #ffffff !important;
        font-weight: 700;
        border-radius: 30px;
        border: none;
        box-shadow: 0 4px 15px rgba(245, 158, 11, 0.4);
        transition: all 0.25s ease;
    }
    .btn-prestige-gold:hover {
        background: linear-gradient(90deg, #d97706 0%, #b45309 100%);
        transform: scale(1.04);
        box-shadow: 0 6px 20px rgba(245, 158, 11, 0.6);
    }
    .executive-stat-card {
        background: #ffffff;
        border-radius: 20px;
        border: 1px solid #e2e8f0;
        box-shadow: 0 8px 25px rgba(30, 41, 59, 0.04);
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }
    .executive-stat-card:hover {
        transform: translateY(-3px);
        box-shadow: 0 12px 30px rgba(30, 58, 138, 0.08);
    }
    .icon-pill-blue {
        width: 48px;
        height: 48px;
        border-radius: 14px;
        background: #eff6ff;
        color: #2563eb;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.4rem;
    }
    .icon-pill-amber {
        width: 48px;
        height: 48px;
        border-radius: 14px;
        background: #fffbe6;
        color: #d97706;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 1.4rem;
    }

    /* ══ DARK MODE COMPATIBILITY & ULTRA READABILITY ══ */
    body.theme-dark .text-dark,
    [data-bs-theme="dark"] .text-dark,
    .theme-dark .text-dark {
        color: #f1f5f9 !important;
    }
    body.theme-dark .text-muted,
    [data-bs-theme="dark"] .text-muted,
    .theme-dark .text-muted {
        color: #94a3b8 !important;
    }
    body.theme-dark h1, [data-bs-theme="dark"] h1,
    body.theme-dark h2, [data-bs-theme="dark"] h2,
    body.theme-dark h3, [data-bs-theme="dark"] h3,
    body.theme-dark h4, [data-bs-theme="dark"] h4,
    body.theme-dark h5, [data-bs-theme="dark"] h5,
    body.theme-dark h6, [data-bs-theme="dark"] h6 {
        color: #f8fafc !important;
    }
    body.theme-dark .executive-stat-card,
    [data-bs-theme="dark"] .executive-stat-card,
    .theme-dark .executive-stat-card {
        background: #1e293b !important;
        border-color: #334155 !important;
    }
    body.theme-dark .executive-stat-card h1,
    body.theme-dark .executive-stat-card h2,
    [data-bs-theme="dark"] .executive-stat-card h1,
    [data-bs-theme="dark"] .executive-stat-card h2 {
        color: #f8fafc !important;
    }
    body.theme-dark .icon-pill-blue,
    [data-bs-theme="dark"] .icon-pill-blue {
        background: #1e3a8a !important;
        color: #93c5fd !important;
    }
    body.theme-dark .icon-pill-amber,
    [data-bs-theme="dark"] .icon-pill-amber {
        background: #78350f !important;
        color: #fde047 !important;
    }
    body.theme-dark .card-header.bg-white,
    [data-bs-theme="dark"] .card-header.bg-white,
    .theme-dark .card-header.bg-white,
    body.theme-dark .card-header,
    [data-bs-theme="dark"] .card-header {
        background-color: #0f172a !important;
        color: #f8fafc !important;
        border-bottom: 1px solid #334155 !important;
    }
    body.theme-dark .card,
    [data-bs-theme="dark"] .card,
    .theme-dark .card {
        background-color: #1e293b !important;
        border-color: #334155 !important;
    }
    body.theme-dark .alert-info,
    [data-bs-theme="dark"] .alert-info {
        background-color: #1e1b4b !important;
        color: #c7d2fe !important;
        border-left: 5px solid #6366f1 !important;
    }
    body.theme-dark .alert-info strong,
    [data-bs-theme="dark"] .alert-info strong,
    body.theme-dark .alert-info .text-dark,
    [data-bs-theme="dark"] .alert-info .text-dark {
        color: #e0e7ff !important;
    }
    body.theme-dark .alert-primary,
    [data-bs-theme="dark"] .alert-primary {
        background-color: #1e3a8a !important;
        color: #bfdbfe !important;
        border-color: #2563eb !important;
    }
    body.theme-dark .table,
    [data-bs-theme="dark"] .table {
        color: #f1f5f9 !important;
    }
    body.theme-dark .table th,
    [data-bs-theme="dark"] .table th {
        background-color: #0f172a !important;
        color: #cbd5e1 !important;
        border-color: #334155 !important;
    }
    body.theme-dark .table td,
    [data-bs-theme="dark"] .table td {
        border-color: #334155 !important;
        color: #f1f5f9 !important;
    }
    body.theme-dark .table-hover tbody tr:hover,
    [data-bs-theme="dark"] .table-hover tbody tr:hover {
        background-color: rgba(255, 255, 255, 0.05) !important;
    }
    body.theme-dark .form-control,
    [data-bs-theme="dark"] .form-control {
        background-color: #0f172a !important;
        border-color: #334155 !important;
        color: #f8fafc !important;
    }
    body.theme-dark label,
    [data-bs-theme="dark"] label {
        color: #f1f5f9 !important;
    }

    .kpi-metric-badge {
        background-color: #f1f5f9;
        color: #334155;
        font-weight: 600;
        padding: 6px 12px;
        border-radius: 8px;
    }
    body.theme-dark .kpi-metric-badge,
    [data-bs-theme="dark"] .kpi-metric-badge,
    .theme-dark .kpi-metric-badge {
        background-color: #0f172a !important;
        background: #0f172a !important;
        color: #f1f5f9 !important;
        border-color: #334155 !important;
    }
    body.theme-dark .badge.bg-light,
    [data-bs-theme="dark"] .badge.bg-light,
    .theme-dark .badge.bg-light {
        background-color: #0f172a !important;
        background: #0f172a !important;
        color: #f1f5f9 !important;
        border-color: #334155 !important;
    }

    /* Soft Pastel Score Badges */
    .score-excellent {
        background-color: #d1fae5 !important;
        color: #065f46 !important;
        border: 1px solid #a7f3d0 !important;
    }
    .score-good {
        background-color: #e0f2fe !important;
        color: #0369a1 !important;
        border: 1px solid #bae6fd !important;
    }
    .score-satisfactory {
        background-color: #fef3c7 !important;
        color: #92400e !important;
        border: 1px solid #fde68a !important;
    }
    .score-unsatisfactory {
        background-color: #ffe4e6 !important;
        color: #9f1239 !important;
        border: 1px solid #fecdd3 !important;
    }

    body.theme-dark .score-excellent, [data-bs-theme="dark"] .score-excellent {
        background-color: rgba(16, 185, 129, 0.18) !important;
        color: #6ee7b7 !important;
        border-color: rgba(16, 185, 129, 0.35) !important;
    }
    body.theme-dark .score-good, [data-bs-theme="dark"] .score-good {
        background-color: rgba(2, 132, 199, 0.18) !important;
        color: #7dd3fc !important;
        border-color: rgba(2, 132, 199, 0.35) !important;
    }
    body.theme-dark .score-satisfactory, [data-bs-theme="dark"] .score-satisfactory {
        background-color: rgba(245, 158, 11, 0.18) !important;
        color: #fcd34d !important;
        border-color: rgba(245, 158, 11, 0.35) !important;
    }
    body.theme-dark .score-unsatisfactory, [data-bs-theme="dark"] .score-unsatisfactory {
        background-color: rgba(244, 63, 94, 0.18) !important;
        color: #fda4af !important;
        border-color: rgba(244, 63, 94, 0.35) !important;
    }
</style>

        <div class="row mb-4">
            <!-- Best Employee Widget (Luxury Executive Hall-of-Fame) -->
            <div class="col-lg-5 col-md-12 mb-3 mb-lg-0">
                <div class="card hall-of-fame-card h-100 border-0">
                    <div class="card-body text-center p-4 d-flex flex-column justify-content-between">
                        <div>
                            <span class="badge prestige-gold-badge px-3 py-2 text-uppercase mb-3 shadow">
                                <i class="bi bi-trophy-fill me-1"></i> EMPLOYEE OF THE MONTH
                            </span>
                            <div class="my-2">
                                @if($bestEmployee && !empty($bestEmployee['photo']))
                                    <div class="position-relative d-inline-block">
                                        <img src="{{ asset('storage/' . $bestEmployee['photo']) }}" alt="{{ $bestEmployee['fullname'] }}" class="rounded-circle shadow-lg" style="width: 82px; height: 82px; object-fit: cover; border: 3.5px solid #fbbf24; box-shadow: 0 0 25px rgba(245, 158, 11, 0.45);" />
                                        <div style="position: absolute; bottom: -2px; right: -4px; background: linear-gradient(135deg, #f59e0b, #d97706); color: #fff; width: 28px; height: 28px; border-radius: 50%; display: flex; align-items: center; justify-content: center; border: 2px solid #0f172a; font-size: 0.85rem; box-shadow: 0 2px 8px rgba(0,0,0,0.4);" title="Champion Trophy">
                                            <i class="bi bi-trophy-fill"></i>
                                        </div>
                                    </div>
                                @else
                                    <div class="trophy-ring">
                                        <i class="bi bi-award-fill"></i>
                                    </div>
                                @endif
                            </div>
                        </div>

                        @if($bestEmployee)
                            <div>
                                <h3 class="text-white fw-bold mb-1" style="font-size: 1.55rem; letter-spacing: -0.3px;">
                                    {{ $bestEmployee['fullname'] }}
                                </h3>
                                <p class="mb-3" style="color: #93c5fd; font-weight: 500; font-size: 0.92rem;">
                                    <i class="bi bi-building me-1"></i> {{ $bestEmployee['department'] }} &bull; {{ $bestEmployee['position'] }}
                                </p>

                                <div class="score-pill-gold rounded-pill px-4 py-2 d-inline-block mb-3">
                                    <span class="text-warning me-1">★</span>
                                    <span class="text-white fw-bold fs-5">{{ round($bestEmployee['composite_score'], 2) }}</span>
                                    <small class="text-white opacity-75 fs-6">/ 100</small>
                                </div>
                            </div>

                            <div>
                                <a href="{{ route('kpi.show', $bestEmployee['employee_id']) }}?period={{ $period }}" class="btn btn-prestige-gold rounded-pill px-4 py-2 btn-sm text-decoration-none">
                                    Lihat Profile & Detail <i class="bi bi-arrow-right-short ms-1 fs-5 align-middle"></i>
                                </a>
                            </div>
                            
                            @if($canGenerate ?? false)
                            <div class="mt-4 pt-3 border-top border-secondary border-opacity-25">
                                <form action="{{ route('kpi.set-dashboard-eotm') }}" method="POST" class="d-flex flex-column align-items-center">
                                    @csrf
                                    <label for="dashboard_period" class="text-white-50 small mb-2"><i class="bi bi-display"></i> Tampilkan di Dashboard Utama</label>
                                    <div class="input-group input-group-sm w-75 mb-1">
                                        <input type="month" name="period" id="dashboard_period" class="form-control text-center bg-dark text-white border-secondary" required value="{{ $period }}">
                                        <button type="submit" class="btn btn-primary fw-bold">Set</button>
                                    </div>
                                    @php
                                        $currentSet = \App\Models\Setting::getValue('dashboard_eotm_period');
                                    @endphp
                                    @if($currentSet)
                                    <small class="text-success" style="font-size: 0.7rem;"><i class="bi bi-check-circle-fill"></i> Aktif di Dashboard: {{ \Carbon\Carbon::createFromFormat('Y-m', $currentSet)->format('F Y') }}</small>
                                    @endif
                                </form>
                            </div>
                            @endif
                        @else
                            <div class="py-4">
                                <h5 class="text-white-50 mb-0">Belum Ada Data KPI</h5>
                            </div>
                        @endif
                    </div>
                </div>
            </div>

            <!-- Stats Summary (Total Monitored & Performance Period) -->
            <div class="col-lg-7 col-md-12">
                <div class="row h-100">
                    <!-- Total Employees Monitored Card -->
                    <div class="col-md-6 mb-3 mb-md-0">
                        <div class="card h-100 executive-stat-card p-4" style="border-left: 5px solid #2563eb !important;">
                            <div class="card-body p-0 d-flex flex-column justify-content-between">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <div class="icon-pill-blue">
                                        <i class="bi bi-people-fill"></i>
                                    </div>
                                    <span class="badge px-3 py-1 rounded-pill fw-bold" style="background: #eff6ff; color: #1d4ed8;">
                                        <i class="bi bi-activity me-1"></i> Active System
                                    </span>
                                </div>

                                <div class="my-2">
                                    <h6 class="fw-bold text-uppercase tracking-wider mb-1" style="font-size: 0.8rem; color: #64748b !important;">
                                        Total Employees Monitored
                                    </h6>
                                    <h1 class="display-4 fw-extrabold mb-0" style="font-size: 2.75rem; color: #1e293b;">
                                        {{ count($kpiData) }}
                                    </h1>
                                </div>

                                <div class="mt-3 pt-3 border-top d-flex align-items-center justify-content-between text-muted" style="font-size: 0.85rem;">
                                    <span><i class="bi bi-shield-check text-primary me-1"></i> Real-time Monitoring</span>
                                    <span class="fw-bold text-dark">{{ count($kpiData) }} Karyawan</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Performance Period Card -->
                    <div class="col-md-6">
                        <div class="card h-100 executive-stat-card p-4" style="border-left: 5px solid #f59e0b !important;">
                            <div class="card-body p-0 d-flex flex-column justify-content-between">
                                <div class="d-flex justify-content-between align-items-center mb-3">
                                    <div class="icon-pill-amber">
                                        <i class="bi bi-calendar2-check-fill"></i>
                                    </div>
                                    <span class="badge px-3 py-1 rounded-pill fw-bold" style="background: #fffbe6; color: #b45309;">
                                        <i class="bi bi-check2-circle me-1"></i> Verified
                                    </span>
                                </div>

                                <div class="my-2">
                                    <h6 class="fw-bold text-uppercase tracking-wider mb-1" style="font-size: 0.8rem; color: #64748b !important;">
                                        Performance Period
                                    </h6>
                                    <h2 class="fw-extrabold mb-0" style="font-size: 1.85rem; color: #1e293b;">
                                        {{ $periodFormatted }}
                                    </h2>
                                </div>

                                <div class="mt-3 pt-3 border-top d-flex align-items-center justify-content-between text-muted" style="font-size: 0.85rem;">
                                    <span><i class="bi bi-pie-chart-fill text-warning me-1"></i> Formulasi 2-Metric</span>
                                    <span class="badge bg-slate-100 text-dark border px-2 py-1" style="background: #f8fafc;">50% + 50%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>   </div>

        <!-- Info Note -->
        <div class="row mb-3">
            <div class="col-12">
                <div class="alert alert-info border-0 shadow-sm" style="background-color: #eef2ff; border-left: 5px solid #4f46e5 !important;">
                    <div class="d-flex align-items-center gap-3">
                        <i class="bi bi-info-circle-fill text-primary fs-4"></i>
                        <div class="text-dark" style="font-size: 0.95rem;">
                            <strong>Catatan Perhitungan:</strong> Nilai <strong>Composite Score</strong> masing-masing karyawan pada tabel di bawah ini merupakan akumulasi performa yang dihitung dari bobot <strong>50% Kepatuhan Checkout Presensi</strong> dan <strong>50% Pengisian Log Pekerjaan Harian</strong>.
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Employee List Table -->
        <div class="row">
            <div class="col-12">
                <div class="card shadow-sm">
                    <div class="card-header bg-white py-3">
                        <h5 class="card-title mb-0">Detailed Employee Performance Metrics</h5>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-hover align-middle mb-0">
                                <thead class="table-light">
                                    <tr>
                                        <th class="px-4">Rank</th>
                                        <th>Employee Name</th>
                                        <th>Department / Role</th>
                                        <th class="text-center">Working Days</th>
                                        <th class="text-center">Log Count</th>
                                        <th>Checkout Compliance</th>
                                        <th>Log Compliance</th>
                                        <th>Composite Score</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($kpiData as $index => $data)
                                    <tr>
                                        <td class="px-4">
                                            @if($index === 0)
                                                <span class="badge bg-warning text-dark px-2 py-1"><i class="bi bi-star-fill"></i> 1</span>
                                            @elseif($index === 1)
                                                <span class="badge bg-secondary px-2 py-1">2</span>
                                            @elseif($index === 2)
                                                <span class="badge text-white px-2 py-1" style="background-color: #cd7f32 !important;">3</span>
                                            @else
                                                <span class="text-muted fw-bold ps-2">{{ $index + 1 }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                @if(!empty($data['photo']))
                                                    <img src="{{ asset('storage/' . $data['photo']) }}" alt="{{ $data['fullname'] }}" class="rounded-circle shadow-sm" style="width: 38px; height: 38px; object-fit: cover; border: 2px solid #e2e8f0;" />
                                                @else
                                                    <div class="rounded-circle bg-primary bg-opacity-10 text-primary fw-bold d-flex align-items-center justify-content-center border" style="width: 38px; height: 38px; font-size: 0.85rem;">
                                                        {{ strtoupper(substr($data['fullname'], 0, 1)) }}
                                                    </div>
                                                @endif
                                                <strong class="text-dark">{{ $data['fullname'] }}</strong>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="fw-bold text-secondary">{{ $data['department'] }}</div>
                                            <small class="text-muted">{{ $data['position'] }}</small>
                                        </td>
                                        <td class="text-center">
                                            <span class="badge kpi-metric-badge border">{{ $data['working_days'] ?? '-' }} Days</span>
                                        </td>
                                        <td class="text-center">
                                            <span class="badge kpi-metric-badge border">{{ $data['log_count'] ?? '-' }} Logs</span>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="text-{{ $data['checkout_percentage'] >= 100 ? 'success' : ($data['checkout_percentage'] >= 75 ? 'warning' : 'danger') }} fw-bold">
                                                    {{ round($data['checkout_percentage'], 1) }}%
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="text-{{ $data['log_percentage'] >= 100 ? 'success' : ($data['log_percentage'] >= 75 ? 'warning' : 'danger') }} fw-bold">
                                                    {{ round($data['log_percentage'], 1) }}%
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <span class="badge rounded-pill bg-{{ $data['composite_score'] >= 80 ? 'success' : ($data['composite_score'] >= 60 ? 'warning' : 'danger') }} px-3 py-2">
                                                {{ round($data['composite_score'], 2) }}
                                            </span>
                                        </td>
                                        <td class="text-center">
                                            <a href="{{ route('kpi.show', $data['employee_id']) }}" class="btn btn-sm btn-outline-primary rounded-pill">Lihat Profile</a>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center py-5 text-muted">
                                            <i class="bi bi-folder2-open" style="font-size: 3rem;"></i>
                                            <p class="mt-3">No KPI Data Available. System will calculate automatically at midnight or run the command manually.</p>
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
</div>

@if($nextUpdate ?? false)
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const nextUpdateStr = "{{ $nextUpdate }}";
        const countDownDate = new Date(nextUpdateStr.replace(/-/g, "/")).getTime(); 

        const timerEl = document.getElementById("countdownTimer");
        
        const x = setInterval(function() {
            const now = new Date().getTime();
            const distance = countDownDate - now;

            if (distance < 0) {
                clearInterval(x);
                timerEl.innerHTML = "Updating now...";
                return;
            }

            const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((distance % (1000 * 60)) / 1000);

            timerEl.innerHTML = hours + "h " + minutes + "m " + seconds + "s";
        }, 1000);
    });
</script>
@endif

@if($canGenerate ?? false)
<!-- Confirmation Modal for Recalculate KPI -->
<div class="modal fade" id="confirmRecalculateModal" tabindex="-1" aria-labelledby="confirmRecalculateModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title fw-bold" id="confirmRecalculateModalLabel">
                    <i class="bi bi-exclamation-triangle-fill me-2"></i>Konfirmasi {{ ($isGenerated ?? false) ? 'Hitung Ulang (Recalculate)' : 'Generate' }} KPI
                </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-4 text-center">
                <div class="mb-3">
                    <i class="bi bi-arrow-repeat text-primary display-3"></i>
                </div>
                <h5 class="fw-bold text-dark mb-2">Apakah Anda yakin ingin mengkalkulasi ulang data KPI?</h5>
                <p class="text-muted mb-0">
                    Proses ini akan menghitung ulang seluruh skor pencapaian absensi dan log kerja harian karyawan untuk periode <strong>{{ $periodFormatted }}</strong>.
                </p>
            </div>
            <div class="modal-footer bg-light border-0 justify-content-center">
                <button type="button" class="btn btn-secondary px-4 rounded-pill" data-bs-dismiss="modal">
                    <i class="bi bi-x-circle me-1"></i> Batal
                </button>
                <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                    @csrf
                    <input type="hidden" name="period" value="{{ $period }}">
                    <button type="submit" class="btn btn-primary px-4 rounded-pill shadow-sm">
                        <i class="bi bi-play-circle-fill me-1"></i> Ya, {{ ($isGenerated ?? false) ? 'Hitung Ulang' : 'Generate' }} Sekarang
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
@endif
@endsection
