@extends('layouts.dashboard')

@section('content')
<div class="page-heading">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h3 class="fw-bold text-dark mb-1">Company KPI Dashboard</h3>
            <p class="text-muted mb-0">Performance monitoring & Employee of the Month across company</p>
        </div>
        <div class="col-md-6 text-right">
            <div class="d-flex justify-content-end align-items-center flex-wrap gap-2">
                <form method="GET" class="form-inline d-flex align-items-center me-2">
                    <label class="me-2 fw-bold text-dark mb-0">Period: </label>
                    <input type="month" name="period" value="{{ $period }}" class="form-control" onchange="this.form.submit()">
                </form>

                @if($canGenerate ?? false)
                <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                    @csrf
                    <input type="hidden" name="period" value="{{ $period }}">
                    <button type="submit" class="btn btn-primary btn-md shadow-sm">
                        <i class="bi bi-play-circle-fill me-1"></i> {{ ($isGenerated ?? false) ? 'Recalculate KPI' : 'Generate KPI Periode Ini' }}
                    </button>
                </form>
                @endif
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container-fluid px-0">
        
        @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show border-0 shadow-sm mb-4" role="alert">
                <i class="bi bi-check-circle-fill me-2"></i> {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif

        @if(!($isGenerated ?? true))
            <!-- Empty State Card when KPI has not been generated by HR -->
            <div class="card border-0 shadow-sm my-4">
                <div class="card-body text-center py-5">
                    <div class="mb-3">
                        <i class="bi bi-calendar-x text-warning display-4"></i>
                    </div>
                    <h4 class="fw-bold text-dark">KPI Belum Digenerate untuk Periode {{ $periodFormatted }}</h4>
                    <p class="text-muted max-w-lg mx-auto mb-4">
                        Laporan KPI dan penentuan Employee of the Month pada periode ini belum diterbitkan oleh HR / Master Admin. <br>
                        Penilaian dihitung secara transparan dari <strong>50% Kepatuhan Checkout Presensi</strong> dan <strong>50% Pengisian Log Kerja Harian</strong>.
                    </p>
                    @if($canGenerate ?? false)
                        <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                            @csrf
                            <input type="hidden" name="period" value="{{ $period }}">
                            <button type="submit" class="btn btn-primary btn-lg px-4 shadow">
                                <i class="bi bi-play-circle-fill me-2"></i> Generate KPI Periode Ini Sekarang
                            </button>
                        </form>
                    @else
                        <span class="badge bg-secondary px-3 py-2 fs-6">Menunggu HR Administrator memproses KPI bulan ini</span>
                    @endif
                </div>
            </div>
        @else
        <!-- System Update Status -->
        <div class="row mb-4">
            <div class="col-12">
                <div class="alert alert-primary d-flex align-items-center justify-content-between border-0 shadow-sm">
                    <div>
                        <i class="bi bi-check-circle-fill me-2"></i>
                        <strong>Last Calculation:</strong> {{ $lastUpdated ? \Carbon\Carbon::parse($lastUpdated)->format('d M Y, H:i') : 'Up to Date' }}
                    </div>
                    <span class="badge bg-white text-primary px-3 py-2 border shadow-sm">
                        <i class="bi bi-layers-fill me-1"></i> Mode: 2 Indikator (Checkout + Log Kerja)
                    </span>
                </div>
            </div>
        </div>

        <div class="row mb-4">
            <!-- Best Employee Widget -->
            <div class="col-md-4">
                <div class="card bg-gradient-primary text-white h-100 border-0 shadow-sm" style="background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);">
                    <div class="card-body text-center p-4">
                        <span class="badge bg-warning text-dark px-3 py-1 fw-bold text-uppercase mb-3 shadow-sm">
                            <i class="bi bi-award-fill me-1"></i> Employee of The Month
                        </span>
                        <div class="mb-3">
                            <i class="bi bi-trophy-fill text-warning" style="font-size: 4rem; filter: drop-shadow(0 4px 10px rgba(255,215,0,0.5));"></i>
                        </div>
                        @if($bestEmployee)
                            <h3 class="text-white fw-bold mb-1">{{ $bestEmployee['fullname'] }}</h3>
                            <p class="text-light opacity-75 mb-3">{{ $bestEmployee['department'] }} • {{ $bestEmployee['position'] }}</p>
                            
                            <div class="bg-white bg-opacity-25 rounded-pill px-4 py-2 d-inline-block shadow-sm mb-3">
                                <h4 class="mb-0 text-white fw-bold">{{ round($bestEmployee['composite_score'], 2) }} <small class="fs-6 fw-normal">/ 100</small></h4>
                            </div>

                            <div>
                                <a href="{{ route('kpi.show', $bestEmployee['employee_id']) }}?period={{ $period }}" class="btn btn-sm btn-light rounded-pill px-4 fw-bold text-primary shadow-sm">Lihat Profile <i class="bi bi-arrow-right ms-1"></i></a>
                            </div>
                        @else
                            <h4 class="text-white mt-4">Data Not Available</h4>
                        @endif
                    </div>
                </div>
            </div>

            <!-- Stats Summary -->
            <div class="col-md-8">
                <div class="row h-100">
                    <div class="col-md-6 mb-3 mb-md-0">
                        <div class="card h-100 border-0 shadow-sm border-left-info">
                            <div class="card-body d-flex flex-column justify-content-center">
                                <h6 class="text-info font-weight-bold mb-1">Total Employees Monitored</h6>
                                <h2 class="mb-0 fw-bold text-dark">{{ count($kpiData) }}</h2>
                                <small class="text-muted">Active Employees in System</small>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card h-100 border-0 shadow-sm border-left-success">
                            <div class="card-body d-flex flex-column justify-content-center">
                                <h6 class="text-success font-weight-bold mb-1">Performance Period</h6>
                                <h2 class="mb-0 fw-bold text-dark">{{ $periodFormatted }}</h2>
                                <small class="text-muted">2-Metric Verified Evaluation</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Info Note -->
        <div class="row mb-3">
            <div class="col-12">
                <div class="alert alert-info border-0 shadow-sm" style="background-color: #eef2ff; border-left: 5px solid #4f46e5 !important;">
                    <div class="d-flex align-items-center gap-3">
                        <i class="bi bi-info-circle-fill text-primary fs-4"></i>
                        <div class="text-dark" style="font-size: 0.95rem;">
                            <strong>Catatan Perhitungan:</strong> Nilai <strong>Composite Score</strong> masing-masing karyawan pada tabel di bawah ini merupakan akumulasi performa yang dihitung dari bobot <strong>50% Kepatuhan Checkout Presensi</strong> dan <strong>50% Pengisian Log Pekerjaan Harian</strong>.
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Employee List Table -->
        <div class="row">
            <div class="col-12">
                <div class="card shadow-sm">
                    <div class="card-header bg-white py-3">
                        <h5 class="card-title mb-0">Detailed Employee Performance Metrics</h5>
                    </div>
                    <div class="card-body p-0">
                        <div class="table-responsive">
                            <table class="table table-hover align-middle mb-0">
                                <thead class="table-light">
                                    <tr>
                                        <th class="px-4">Rank</th>
                                        <th>Employee Name</th>
                                        <th>Department / Role</th>
                                        <th class="text-center">Working Days</th>
                                        <th class="text-center">Log Count</th>
                                        <th>Checkout Compliance</th>
                                        <th>Log Compliance</th>
                                        <th>Composite Score</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($kpiData as $index => $data)
                                    <tr>
                                        <td class="px-4">
                                            @if($index === 0)
                                                <span class="badge bg-warning text-dark px-2 py-1"><i class="bi bi-star-fill"></i> 1</span>
                                            @elseif($index === 1)
                                                <span class="badge bg-secondary px-2 py-1">2</span>
                                            @elseif($index === 2)
                                                <span class="badge text-white px-2 py-1" style="background-color: #cd7f32 !important;">3</span>
                                            @else
                                                <span class="text-muted fw-bold ps-2">{{ $index + 1 }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <strong class="text-dark">{{ $data['fullname'] }}</strong>
                                        </td>
                                        <td>
                                            <div class="fw-bold text-secondary">{{ $data['department'] }}</div>
                                            <small class="text-muted">{{ $data['position'] }}</small>
                                        </td>
                                        <td class="text-center">
                                            <span class="badge bg-light text-dark border">{{ $data['working_days'] ?? '-' }} Days</span>
                                        </td>
                                        <td class="text-center">
                                            <span class="badge bg-light text-dark border">{{ $data['log_count'] ?? '-' }} Logs</span>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="text-{{ $data['checkout_percentage'] >= 100 ? 'success' : ($data['checkout_percentage'] >= 75 ? 'warning' : 'danger') }} fw-bold">
                                                    {{ round($data['checkout_percentage'], 1) }}%
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="text-{{ $data['log_percentage'] >= 100 ? 'success' : ($data['log_percentage'] >= 75 ? 'warning' : 'danger') }} fw-bold">
                                                    {{ round($data['log_percentage'], 1) }}%
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            <span class="badge rounded-pill bg-{{ $data['composite_score'] >= 80 ? 'success' : ($data['composite_score'] >= 60 ? 'warning' : 'danger') }} px-3 py-2">
                                                {{ round($data['composite_score'], 2) }}
                                            </span>
                                        </td>
                                        <td class="text-center">
                                            <a href="{{ route('kpi.show', $data['employee_id']) }}" class="btn btn-sm btn-outline-primary rounded-pill">Lihat Profile</a>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="9" class="text-center py-5 text-muted">
                                            <i class="bi bi-folder2-open" style="font-size: 3rem;"></i>
                                            <p class="mt-3">No KPI Data Available. System will calculate automatically at midnight or run the command manually.</p>
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endif
    </div>
</div>

@if($nextUpdate ?? false)
<script>
    document.addEventListener("DOMContentLoaded", function() {
        const nextUpdateStr = "{{ $nextUpdate }}";
        const countDownDate = new Date(nextUpdateStr.replace(/-/g, "/")).getTime(); 

        const timerEl = document.getElementById("countdownTimer");
        
        const x = setInterval(function() {
            const now = new Date().getTime();
            const distance = countDownDate - now;

            if (distance < 0) {
                clearInterval(x);
                timerEl.innerHTML = "Updating now...";
                return;
            }

            const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((distance % (1000 * 60)) / 1000);

            timerEl.innerHTML = hours + "h " + minutes + "m " + seconds + "s";
        }, 1000);
    });
</script>
@endif
@endsection
