@extends('layouts.dashboard')

@section('content')
<div class="page-heading">
    <div class="row align-items-center mb-3">
        <div class="col-md-4">
            <h3 class="fw-bold text-dark mb-1">Department Performance Analysis</h3>
            <p class="text-muted mb-0">
                <strong>{{ $selectedDepartment ? $selectedDepartment->name : 'Semua Departemen' }}</strong> • {{ \Carbon\Carbon::createFromFormat('Y-m', $period)->format('F Y') }}
            </p>
        </div>
        <div class="col-md-8 text-right">
            <div class="d-flex justify-content-end align-items-center flex-wrap gap-2">
                <form method="GET" class="d-flex align-items-center gap-1 me-1" id="deptFilterForm">
                    <input type="hidden" name="period" value="{{ $period }}">
                    <label class="fw-bold text-dark mb-0 me-1">Dept: </label>
                    <select name="department_id" class="form-select form-control me-2" style="width: 170px;" onchange="this.form.submit()">
                        <option value="all" {{ ($selectedDeptId ?? 'all') == 'all' ? 'selected' : '' }}>Semua Departemen</option>
                        @foreach($departments ?? [] as $dept)
                            <option value="{{ $dept->id }}" {{ ($selectedDeptId ?? '') == $dept->id ? 'selected' : '' }}>{{ $dept->name }}</option>
                        @endforeach
                    </select>
                </form>

                @if(($canGenerate ?? false) && ($selectedDeptId ?? 'all') !== 'all')
                <form action="{{ route('kpi.department.delete', $selectedDeptId) }}" method="POST" class="d-inline" onsubmit="return confirm('Apakah Anda yakin ingin menghapus {{ $selectedDepartment ? "Departemen {$selectedDepartment->name}" : "Departemen ini" }}? Seluruh anggota departemen akan dilepas.')">
                    @csrf
                    <input type="hidden" name="period" value="{{ $period }}">
                    <button type="submit" class="btn btn-outline-danger btn-md shadow-sm me-1" title="Hapus Departemen Ini">
                        <i class="bi bi-trash-fill me-1"></i> Hapus Dept
                    </button>
                </form>
                @endif

                <div class="d-flex align-items-center me-2">
                    <label class="me-2 fw-bold text-dark mb-0">Periode: </label>
                    <input type="month" id="periodSelect" class="form-control" value="{{ $period }}" onchange="changePeriod()">
                </div>

                @if($canGenerate ?? false)
                <button type="button" class="btn btn-success btn-md shadow-sm me-1" data-bs-toggle="modal" data-bs-target="#manageDepartmentModal">
                    <i class="bi bi-building-add me-1"></i> + Buat / Kelola Dept
                </button>
                @endif
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container-fluid px-0">
        @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show border-0 shadow-sm mb-4" role="alert">
                <i class="bi bi-check-circle-fill me-2"></i> {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if(session('error'))
            <div class="alert alert-danger alert-dismissible fade show border-0 shadow-sm mb-4" role="alert">
                <i class="bi bi-exclamation-triangle-fill me-2"></i> {{ session('error') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if(!($isGenerated ?? true))
            <!-- Empty State Card when KPI has not been generated by HR -->
            <div class="card border-0 shadow-sm my-4">
                <div class="card-body text-center py-5">
                    <div class="mb-3">
                        <i class="bi bi-calendar-x text-warning display-4"></i>
                    </div>
                    <h4 class="fw-bold text-dark">KPI Departemen Belum Digenerate untuk Periode {{ \Carbon\Carbon::createFromFormat('Y-m', $period)->format('F Y') }}</h4>
                    <p class="text-muted max-w-lg mx-auto mb-4">
                        Laporan KPI departemen pada periode ini belum diterbitkan oleh HR / Master Admin. <br>
                        Penilaian dihitung transparan dari <strong>50% Kepatuhan Checkout Presensi</strong> dan <strong>50% Pengisian Log Kerja Harian</strong>.
                    </p>
                    @if($canGenerate ?? false)
                        <a href="{{ route('kpi.company') }}?period={{ $period }}" class="btn btn-primary btn-lg px-4 shadow">
                            <i class="bi bi-box-arrow-up-right me-2"></i> Buka Company KPI untuk Generate
                        </a>
                    @else
                        <span class="badge bg-secondary px-3 py-2 fs-6">Menunggu HR Administrator memproses KPI bulan ini</span>
                    @endif
                </div>
            </div>
        @else

        <!-- Department Summary -->
        <div class="row mb-4">
            <div class="col-md-3">
                <div class="card border-left-primary">
                    <div class="card-body">
                        <h6 class="text-primary font-weight-bold mb-1">Total Employees</h6>
                        <h2 class="mb-0">{{ count($deptEmployees) }}</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-left-success">
                    <div class="card-body">
                        <h6 class="text-success font-weight-bold mb-1">Department Average</h6>
                        <h2 class="mb-0">{{ round($avgScore, 2) }}/100</h2>
                        <small class="text-muted">Overall Performance</small>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-left-info">
                    <div class="card-body">
                        <h6 class="text-info font-weight-bold mb-1">Highest Performer</h6>
                        @php
                            $highest = $deptKPIs->sortByDesc('composite_score')->first();
                        @endphp
                        <h4 class="mb-0">{{ round($highest['composite_score'] ?? 0, 2) }}</h4>
                        <small class="text-muted">{{ $highest['employee']->fullname ?? 'N/A' }}</small>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-left-warning">
                    <div class="card-body">
                        <h6 class="text-warning font-weight-bold mb-1">Performance Trend</h6>
                        <h4 class="mb-0">
                            @php
                                $excellent = collect($deptKPIs)->where('performance_level', 'excellent')->count();
                                if($excellent > 0) {
                                    echo '<i class="bi bi-arrow-up text-success"></i> +' . $excellent;
                                } else {
                                    echo '<i class="bi bi-dash text-muted"></i> Stable';
                                }
                            @endphp
                        </h4>
                    </div>
                </div>
            </div>
        </div>

        <!-- Department Performance Table -->
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Employee Performance Rankings</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead class="table-light">
                                    <tr>
                                        <th style="width: 40px;">Rank</th>
                                        <th>Employee</th>
                                        <th style="width: 120px;">Position</th>
                                        <th style="width: 150px;">Composite Score</th>
                                        <th style="width: 140px;">Performance Level</th>
                                        <th style="width: 200px;">Score Distribution</th>
                                        <th style="width: 100px;">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($deptKPIs as $index => $kpi)
                                    <tr>
                                        <td>
                                            @if($index === 0)
                                                <span class="badge bg-warning"><i class="bi bi-trophy"></i></span>
                                            @else
                                                <strong>{{ $index + 1 }}</strong>
                                            @endif
                                        </td>
                                        <td>
                                            <strong>{{ $kpi['employee']->fullname }}</strong>
                                            <br><small class="text-muted">{{ $kpi['employee']->employee_id ?? 'N/A' }}</small>
                                        </td>
                                        <td>{{ $kpi['employee']->role?->title ?? 'N/A' }}</td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="badge bg-{{ 
                                                    $kpi['composite_score'] >= 90 ? 'success text-white' : 
                                                    ($kpi['composite_score'] >= 75 ? 'info text-white' : 
                                                    ($kpi['composite_score'] >= 60 ? 'warning text-dark' : 'danger text-white'))
                                                }} fs-6 px-3 py-2">
                                                    {{ round($kpi['composite_score'], 2) }}
                                                </span>
                                            </div>
                                        </td>
                                        <td>
                                            @switch($kpi['performance_level'])
                                                @case('excellent')
                                                    <span class="badge bg-success">Excellent</span>
                                                    @break
                                                @case('good')
                                                    <span class="badge bg-info">Good</span>
                                                    @break
                                                @case('satisfactory')
                                                    <span class="badge bg-warning">Satisfactory</span>
                                                    @break
                                                @case('needs_improvement')
                                                    <span class="badge bg-warning">Needs Improvement</span>
                                                    @break
                                                @default
                                                    <span class="badge bg-danger">Unsatisfactory</span>
                                            @endswitch
                                        </td>
                                        <td>
                                            <div class="progress" style="height: 20px;">
                                                <div class="progress-bar {{ 
                                                    $kpi['composite_score'] >= 90 ? 'bg-success' : 
                                                    ($kpi['composite_score'] >= 75 ? 'bg-info' : 
                                                    ($kpi['composite_score'] >= 60 ? 'bg-warning' : 'bg-danger'))
                                                }}" style="width: {{ min($kpi['composite_score'], 100) }}%;">
                                                    {{ round($kpi['composite_score'], 1) }}%
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <a href="{{ route('kpi.show', $kpi['employee']->id) }}?period={{ $period }}" 
                                               class="btn btn-sm btn-outline-info">
                                                <i class="bi bi-eye"></i> Details
                                            </a>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="7" class="text-center text-muted py-4">
                                            <i class="bi bi-inbox fs-2"></i><br>No employees in this department
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Performance Distribution & Statistics -->
        <div class="row mb-4">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Performance Distribution</h5>
                    </div>
                    <div class="card-body">
                        @php
                            $excellent = collect($deptKPIs)->where('performance_level', 'excellent')->count();
                            $good = collect($deptKPIs)->where('performance_level', 'good')->count();
                            $satisfactory = collect($deptKPIs)->where('performance_level', 'satisfactory')->count();
                            $needsImprovement = collect($deptKPIs)->where('performance_level', 'needs_improvement')->count();
                            $unsatisfactory = collect($deptKPIs)->where('performance_level', 'unsatisfactory')->count();
                            $total = count($deptKPIs);
                        @endphp
                        
                        <div class="list-group list-group-flush">
                            <div class="list-group-item px-0">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <div>
                                        <span class="badge bg-success me-2">{{ $excellent }}</span>
                                        <span>Excellent (90-100)</span>
                                    </div>
                                    <span class="text-muted">{{ round(($excellent/$total)*100, 1) }}%</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-success" style="width: {{ ($excellent/$total)*100 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item px-0">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <div>
                                        <span class="badge bg-info me-2">{{ $good }}</span>
                                        <span>Good (75-89)</span>
                                    </div>
                                    <span class="text-muted">{{ round(($good/$total)*100, 1) }}%</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-info" style="width: {{ ($good/$total)*100 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item px-0">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <div>
                                        <span class="badge bg-warning me-2">{{ $satisfactory }}</span>
                                        <span>Satisfactory (60-74)</span>
                                    </div>
                                    <span class="text-muted">{{ round(($satisfactory/$total)*100, 1) }}%</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-warning" style="width: {{ ($satisfactory/$total)*100 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item px-0">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <div>
                                        <span class="badge bg-warning me-2">{{ $needsImprovement }}</span>
                                        <span>Needs Improvement (45-59)</span>
                                    </div>
                                    <span class="text-muted">{{ round(($needsImprovement/$total)*100, 1) }}%</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-warning" style="width: {{ ($needsImprovement/$total)*100 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item px-0">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <div>
                                        <span class="badge bg-danger me-2">{{ $unsatisfactory }}</span>
                                        <span>Unsatisfactory (&lt;45)</span>
                                    </div>
                                    <span class="text-muted">{{ round(($unsatisfactory/$total)*100, 1) }}%</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-danger" style="width: {{ ($unsatisfactory/$total)*100 }}%;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Department Statistics</h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group list-group-flush">
                            <div class="list-group-item px-0">
                                <span class="text-muted">Average Score:</span>
                                <strong class="float-end">{{ round($avgScore, 2) }}/100</strong>
                            </div>
                            <div class="list-group-item px-0">
                                <span class="text-muted">Highest Score:</span>
                                <strong class="float-end text-success">
                                    {{ round(collect($deptKPIs)->max('composite_score'), 2) }}/100
                                </strong>
                            </div>
                            <div class="list-group-item px-0">
                                <span class="text-muted">Lowest Score:</span>
                                <strong class="float-end text-danger">
                                    {{ round(collect($deptKPIs)->min('composite_score'), 2) }}/100
                                </strong>
                            </div>
                            <div class="list-group-item px-0">
                                <span class="text-muted">Standard Deviation:</span>
                                @php
                                    $scores = collect($deptKPIs)->pluck('composite_score');
                                    $mean = $scores->avg();
                                    $variance = $scores->map(fn($x) => pow($x - $mean, 2))->avg();
                                    $stdDev = sqrt($variance);
                                @endphp
                                <strong class="float-end">{{ round($stdDev, 2) }}</strong>
                            </div>
                            <div class="list-group-item px-0">
                                <span class="text-muted">Total Employees:</span>
                                <strong class="float-end">{{ count($deptEmployees) }}</strong>
                            </div>
                            <div class="list-group-item px-0">
                                <span class="text-muted">Employees Above Average:</span>
                                <strong class="float-end text-success">
                                    {{ collect($deptKPIs)->where('composite_score', '>', $avgScore)->count() }}
                                </strong>
                            </div>
                            <div class="list-group-item px-0">
                                <span class="text-muted">Employees Below Average:</span>
                                <strong class="float-end text-danger">
                                    {{ collect($deptKPIs)->where('composite_score', '<', $avgScore)->count() }}
                                </strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <a href="{{ route('reports.export-csv') }}?period={{ $period }}" class="btn btn-outline-success">
                    <i class="bi bi-download"></i> Export Department Data
                </a>
                <a href="{{ route('kpi.dashboard') }}" class="btn btn-outline-secondary">
                    <i class="bi bi-arrow-left"></i> Back to Dashboard
                </a>
            </div>
        </div>
        @endif
    </div>
</div>

<script>
    function changePeriod() {
        const period = document.getElementById('periodSelect').value;
        const deptId = "{{ $selectedDeptId ?? 'all' }}";
        window.location.href = `{{ route('kpi.department') }}?period=${period}&department_id=${deptId}`;
    }
</script>

@if($canGenerate ?? false)
<!-- Modal Manage Department -->
<div class="modal fade" id="manageDepartmentModal" tabindex="-1" aria-labelledby="manageDepartmentModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content border-0 shadow-lg">
            <form action="{{ route('kpi.department.assign') }}" method="POST">
                @csrf
                <input type="hidden" name="period" value="{{ $period }}">
                
                <div class="modal-header bg-success text-white py-3">
                    <h5 class="modal-title fw-bold text-white mb-0" id="manageDepartmentModalLabel">
                        <i class="bi bi-building-gear me-2"></i> Formasi Structure Departemen
                    </h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body p-4">
                    <div class="alert alert-info border-0 mb-4" style="background-color: #e2e8f0; color: #0f172a !important;">
                        <i class="bi bi-info-circle-fill text-primary me-2"></i>
                        <span style="color: #0f172a !important;">Pilih <strong style="color: #0f172a !important;">Departemen Eksisting</strong> atau ketik <strong style="color: #0f172a !important;">Nama Departemen Baru</strong>, lalu centang karyawan untuk dimasukkan ke departemen tersebut.</span>
                    </div>

                    <div class="row mb-4">
                        <div class="col-md-6 mb-3 mb-md-0">
                            <label class="form-label fw-bold text-dark" style="color: #0f172a !important;">Pilih Departemen Eksisting</label>
                            <select name="department_id" id="modalDeptSelect" class="form-select form-control text-dark" style="color: #0f172a !important; font-weight: 600;" onchange="onModalDeptChange()">
                                <option value="" selected>-- Pilih Departemen Eksisting --</option>
                                @foreach($departments ?? [] as $dept)
                                    <option value="{{ $dept->id }}" {{ ($selectedDeptId != 'all' && $selectedDeptId == $dept->id) ? 'selected' : '' }}>
                                        {{ $dept->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="col-md-6">
                            <label class="form-label fw-bold text-dark" style="color: #0f172a !important;">Atau Ketik Nama Departemen Baru</label>
                            <input type="text" name="new_department_name" id="modalNewDeptInput" class="form-control text-dark" style="color: #0f172a !important; font-weight: 600;" placeholder="Contoh: Research & Development" oninput="onNewDeptInput()">
                        </div>
                    </div>

                    <div class="mb-3">
                        <div class="d-flex justify-content-between align-items-center mb-2">
                            <label class="form-label fw-bold text-dark mb-0" style="color: #0f172a !important;">Pilih Anggota Departemen</label>
                            <span class="text-muted small" style="color: #475569 !important;">Centang karyawan yang merupakan bagian dari departemen ini</span>
                        </div>
                        
                        <div class="border rounded p-3 bg-light" style="max-height: 250px; overflow-y: auto; background-color: #f8fafc !important;">
                            @foreach($allEmployees ?? [] as $member)
                                <div class="form-check py-1 border-bottom border-light dept-member-checkbox-item" data-dept-id="{{ $member->department_id }}">
                                    <input class="form-check-input dept-member-checkbox" type="checkbox" name="member_ids[]" value="{{ $member->id }}" id="dept_member_{{ $member->id }}">
                                    <label class="form-check-label fw-bold ms-2" for="dept_member_{{ $member->id }}" style="color: #0f172a !important;">
                                        {{ $member->fullname }}
                                        <small class="font-weight-normal ms-2" style="color: #475569 !important;">({{ $member->department->name ?? 'Belum Ada Dept' }} • {{ $member->position->name ?? ($member->role->title ?? '-') }})</small>
                                    </label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer bg-light px-4 py-3 justify-content-between">
                    <div>
                        <button type="button" class="btn btn-outline-danger rounded-pill px-3" id="btnDissolveDept" onclick="dissolveSelectedDept()" style="display: none;">
                            <i class="bi bi-trash-fill me-1"></i> Hapus / Bubarkan Departemen Ini
                        </button>
                    </div>
                    <div>
                        <button type="button" class="btn btn-secondary rounded-pill px-4 me-2" data-bs-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-success rounded-pill px-4 shadow-sm">
                            <i class="bi bi-check-circle-fill me-1"></i> Simpan Formasi Departemen
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function onNewDeptInput() {
        const input = document.getElementById('modalNewDeptInput');
        const select = document.getElementById('modalDeptSelect');
        const dissolveBtn = document.getElementById('btnDissolveDept');
        if (input.value.trim() !== '') {
            select.value = '';
            if (dissolveBtn) dissolveBtn.style.display = 'none';
        }
    }

    function dissolveSelectedDept() {
        const select = document.getElementById('modalDeptSelect');
        const selectedDeptId = select.value;
        if (!selectedDeptId) return;
        if (confirm('Apakah Anda yakin ingin menghapus departemen ini? Seluruh anggota departemen akan dilepas.')) {
            const form = document.createElement('form');
            form.method = 'POST';
            form.action = `{{ url('/kpi/department/delete') }}/${selectedDeptId}`;
            
            const csrf = document.createElement('input');
            csrf.type = 'hidden';
            csrf.name = '_token';
            csrf.value = '{{ csrf_token() }}';
            form.appendChild(csrf);

            document.body.appendChild(form);
            form.submit();
        }
    }

    function onModalDeptChange() {
        const select = document.getElementById('modalDeptSelect');
        const selectedDeptId = select.value;
        const input = document.getElementById('modalNewDeptInput');
        const dissolveBtn = document.getElementById('btnDissolveDept');

        if (selectedDeptId) {
            input.value = '';
            if (dissolveBtn) dissolveBtn.style.display = 'inline-block';
        } else {
            if (dissolveBtn) dissolveBtn.style.display = 'none';
        }

        const items = document.querySelectorAll('.dept-member-checkbox-item');
        items.forEach(item => {
            const currentDeptId = item.getAttribute('data-dept-id');
            const checkbox = item.querySelector('.dept-member-checkbox');
            
            if (selectedDeptId && currentDeptId == selectedDeptId) {
                checkbox.checked = true;
            } else if (selectedDeptId) {
                checkbox.checked = false;
            }
        });
    }

    document.addEventListener("DOMContentLoaded", function() {
        if (document.getElementById('modalDeptSelect') && document.getElementById('modalDeptSelect').value) {
            onModalDeptChange();
        }
    });
</script>
@endif
@endsection
