@extends('layouts.dashboard')

@section('content')
<div class="page-heading">
    <div class="row align-items-center mb-3">
        <div class="col-md-5">
            <h3 class="fw-bold text-dark mb-1">Team Performance Overview</h3>
            <p class="text-muted mb-0">
                <strong>{{ $selectedSupervisor ? "Tim {$selectedSupervisor->fullname}" : 'Seluruh Tim Perusahaan' }}</strong> • {{ \Carbon\Carbon::createFromFormat('Y-m', $period)->format('F Y') }}
            </p>
        </div>
        <div class="col-md-7 text-right">
            <div class="d-flex justify-content-end align-items-center flex-wrap gap-2">
                @if(($canGenerate ?? false) || count($supervisors ?? []) > 0)
                <form method="GET" class="d-flex align-items-center gap-1 me-1" id="teamFilterForm">
                    <input type="hidden" name="period" value="{{ $period }}">
                    <label class="fw-bold text-dark mb-0 me-1">Tim: </label>
                    <select name="supervisor_id" class="form-select form-control me-2" style="width: 180px;" onchange="this.form.submit()">
                        <option value="all" {{ ($selectedSupervisorId ?? 'all') == 'all' ? 'selected' : '' }}>Seluruh Tim</option>
                        @foreach($supervisors ?? [] as $sup)
                            <option value="{{ $sup->id }}" {{ ($selectedSupervisorId ?? '') == $sup->id ? 'selected' : '' }}>Tim {{ $sup->fullname }}</option>
                        @endforeach
                    </select>
                </form>

                @if(($canGenerate ?? false) && ($selectedSupervisorId ?? 'all') !== 'all')
                <form action="{{ route('kpi.team.delete', $selectedSupervisorId) }}" method="POST" class="d-inline" onsubmit="return confirm('Apakah Anda yakin ingin membubarkan {{ $selectedSupervisor ? "Tim {$selectedSupervisor->fullname}" : "Tim ini" }}? Seluruh anggota tim akan dilepas.')">
                    @csrf
                    <input type="hidden" name="period" value="{{ $period }}">
                    <button type="submit" class="btn btn-outline-danger btn-md shadow-sm me-2" title="Bubarkan Tim Ini">
                        <i class="bi bi-trash-fill me-1"></i> Hapus Tim
                    </button>
                </form>
                @endif
                @endif

                <div class="d-flex align-items-center me-2">
                    <label class="me-2 fw-bold text-dark mb-0">Periode: </label>
                    <input type="month" id="periodSelect" class="form-control" value="{{ $period }}" onchange="changePeriod()">
                </div>

                @if($canGenerate ?? false)
                <button type="button" class="btn btn-success btn-md shadow-sm me-1" data-bs-toggle="modal" data-bs-target="#manageTeamModal">
                    <i class="bi bi-person-plus-fill me-1"></i> + Buat / Kelola Tim
                </button>

                <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                    @csrf
                    <input type="hidden" name="period" value="{{ $period }}">
                    <button type="submit" class="btn btn-primary btn-md shadow-sm">
                        <i class="bi bi-play-circle-fill me-1"></i> {{ ($isGenerated ?? false) ? 'Recalculate KPI' : 'Generate KPI Periode Ini' }}
                    </button>
                </form>
                @endif
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container-fluid px-0">
        @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show border-0 shadow-sm mb-4" role="alert">
                <i class="bi bi-check-circle-fill me-2"></i> {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif
        @if(!($isGenerated ?? true))
            <!-- Empty State Card when KPI has not been generated by HR -->
            <div class="card border-0 shadow-sm my-4">
                <div class="card-body text-center py-5">
                    <div class="mb-3">
                        <i class="bi bi-calendar-x text-warning display-4"></i>
                    </div>
                    <h4 class="fw-bold text-dark">KPI Tim Belum Digenerate untuk Periode {{ \Carbon\Carbon::createFromFormat('Y-m', $period)->format('F Y') }}</h4>
                    <p class="text-muted max-w-lg mx-auto mb-4">
                        Laporan KPI tim pada periode ini belum diterbitkan oleh HR / Master Admin. <br>
                        Penilaian dihitung transparan dari <strong>50% Kepatuhan Checkout Presensi</strong> dan <strong>50% Pengisian Log Kerja Harian</strong>.
                    </p>
                    @if($canGenerate ?? false)
                        <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                            @csrf
                            <input type="hidden" name="period" value="{{ $period }}">
                            <button type="submit" class="btn btn-primary btn-lg px-4 shadow">
                                <i class="bi bi-play-circle-fill me-2"></i> Generate KPI Periode Ini Sekarang
                            </button>
                        </form>
                    @else
                        <span class="badge bg-secondary px-3 py-2 fs-6">Menunggu HR Administrator memproses KPI bulan ini</span>
                    @endif
                </div>
            </div>
        @else

        <!-- Summary Stats -->
        <div class="row mb-4">
            <div class="col-md-3">
                <div class="card border-left-primary">
                    <div class="card-body">
                        <h6 class="text-primary font-weight-bold mb-1">Total Team Members</h6>
                        <h2 class="mb-0">{{ count($teamMembers) }}</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-left-success">
                    <div class="card-body">
                        <h6 class="text-success font-weight-bold mb-1">Excellent Performers</h6>
                        <h2 class="mb-0">{{ $teamKPIs->where('performance_level', 'excellent')->count() }}</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-left-info">
                    <div class="card-body">
                        <h6 class="text-info font-weight-bold mb-1">Good Performers</h6>
                        <h2 class="mb-0">{{ $teamKPIs->where('performance_level', 'good')->count() }}</h2>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card border-left-warning">
                    <div class="card-body">
                        <h6 class="text-warning font-weight-bold mb-1">Avg Team Score</h6>
                        <h2 class="mb-0">{{ round($teamKPIs->avg('composite_score'), 2) }}/100</h2>
                    </div>
                </div>
            </div>
        </div>

        <!-- Team Performance Table -->
        <div class="row mb-4">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Team Member Performance Rankings</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-striped">
                                <thead class="table-light">
                                    <tr>
                                        <th style="width: 50px;">Rank</th>
                                        <th>Employee Name</th>
                                        <th style="width: 120px;">Position</th>
                                        <th style="width: 150px;">Composite Score</th>
                                        <th style="width: 150px;">Performance Level</th>
                                        <th style="width: 200px;">Trend</th>
                                        <th style="width: 100px;">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($teamKPIs as $index => $kpi)
                                    <tr>
                                        <td>
                                            @if($index === 0)
                                                <span class="badge bg-warning"><i class="bi bi-trophy"></i> Top</span>
                                            @elseif($index === count($teamKPIs) - 1)
                                                <span class="badge bg-info">{{ $index + 1 }}</span>
                                            @else
                                                <span>{{ $index + 1 }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <strong>{{ $kpi['employee']->fullname }}</strong>
                                            <br><small class="text-muted">ID: {{ $kpi['employee']->employee_id ?? 'N/A' }}</small>
                                        </td>
                                        <td>{{ $kpi['employee']->role?->title ?? 'N/A' }}</td>
                                        <td>
                                            <div class="d-flex align-items-center gap-2">
                                                <span class="badge bg-{{ 
                                                    $kpi['composite_score'] >= 90 ? 'success text-white' : 
                                                    ($kpi['composite_score'] >= 75 ? 'info text-white' : 
                                                    ($kpi['composite_score'] >= 60 ? 'warning text-dark' : 'danger text-white'))
                                                }} fs-6 px-3 py-2">
                                                    {{ round($kpi['composite_score'], 2) }}
                                                </span>
                                                <div class="progress" style="width: 100px; height: 20px;">
                                                    <div class="progress-bar {{ 
                                                        $kpi['composite_score'] >= 90 ? 'bg-success' : 
                                                        ($kpi['composite_score'] >= 75 ? 'bg-info' : 
                                                        ($kpi['composite_score'] >= 60 ? 'bg-warning' : 'bg-danger'))
                                                    }}" style="width: {{ min($kpi['composite_score'], 100) }}%;"></div>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            @switch($kpi['performance_level'])
                                                @case('excellent')
                                                    <span class="badge bg-success">Excellent</span>
                                                    @break
                                                @case('good')
                                                    <span class="badge bg-info">Good</span>
                                                    @break
                                                @case('satisfactory')
                                                    <span class="badge bg-warning">Satisfactory</span>
                                                    @break
                                                @case('needs_improvement')
                                                    <span class="badge bg-warning">Needs Improvement</span>
                                                    @break
                                                @default
                                                    <span class="badge bg-danger">Unsatisfactory</span>
                                            @endswitch
                                        </td>
                                        <td>
                                            <div class="spark-chart" style="width: 100%; height: 30px;">
                                                <canvas id="chart-{{ $kpi['employee']->id }}" style="max-height: 30px;"></canvas>
                                            </div>
                                        </td>
                                        <td>
                                            <a href="{{ route('kpi.show', $kpi['employee']->id) }}?period={{ $period }}" 
                                               class="btn btn-sm btn-outline-info">
                                                <i class="bi bi-eye"></i> View Details
                                            </a>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="7" class="text-center text-muted py-4">
                                            <i class="bi bi-inbox fs-2"></i><br>No team members found
                                        </td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Performance Distribution -->
        <div class="row mb-4">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Performance Distribution</h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            @php
                                $excellent = $teamKPIs->where('performance_level', 'excellent')->count();
                                $good = $teamKPIs->where('performance_level', 'good')->count();
                                $satisfactory = $teamKPIs->where('performance_level', 'satisfactory')->count();
                                $needsImprovement = $teamKPIs->where('performance_level', 'needs_improvement')->count();
                                $unsatisfactory = $teamKPIs->where('performance_level', 'unsatisfactory')->count();
                                $total = $excellent + $good + $satisfactory + $needsImprovement + $unsatisfactory;
                            @endphp
                            
                            <div class="list-group-item">
                                <div class="d-flex justify-content-between mb-2">
                                    <span><i class="bi bi-star-fill text-success"></i> Excellent</span>
                                    <span>{{ $excellent }}/{{ $total }} ({{ $total > 0 ? round(($excellent/$total)*100, 1) : 0 }}%)</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-success" style="width: {{ $total > 0 ? ($excellent/$total)*100 : 0 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item">
                                <div class="d-flex justify-content-between mb-2">
                                    <span><i class="bi bi-hand-thumbs-up-fill text-info"></i> Good</span>
                                    <span>{{ $good }}/{{ $total }} ({{ $total > 0 ? round(($good/$total)*100, 1) : 0 }}%)</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-info" style="width: {{ $total > 0 ? ($good/$total)*100 : 0 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item">
                                <div class="d-flex justify-content-between mb-2">
                                    <span><i class="bi bi-check-circle-fill text-warning"></i> Satisfactory</span>
                                    <span>{{ $satisfactory }}/{{ $total }} ({{ $total > 0 ? round(($satisfactory/$total)*100, 1) : 0 }}%)</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-warning" style="width: {{ $total > 0 ? ($satisfactory/$total)*100 : 0 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item">
                                <div class="d-flex justify-content-between mb-2">
                                    <span><i class="bi bi-arrow-up-circle-fill text-orange"></i> Needs Improvement</span>
                                    <span>{{ $needsImprovement }}/{{ $total }} ({{ $total > 0 ? round(($needsImprovement/$total)*100, 1) : 0 }}%)</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-orange" style="width: {{ $total > 0 ? ($needsImprovement/$total)*100 : 0 }}%;"></div>
                                </div>
                            </div>

                            <div class="list-group-item">
                                <div class="d-flex justify-content-between mb-2">
                                    <span><i class="bi bi-x-circle-fill text-danger"></i> Unsatisfactory</span>
                                    <span>{{ $unsatisfactory }}/{{ $total }} ({{ $total > 0 ? round(($unsatisfactory/$total)*100, 1) : 0 }}%)</span>
                                </div>
                                <div class="progress" style="height: 8px;">
                                    <div class="progress-bar bg-danger" style="width: {{ $total > 0 ? ($unsatisfactory/$total)*100 : 0 }}%;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h5 class="card-title mb-0">Team Score Statistics</h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            <div class="list-group-item">
                                <span class="text-muted">Highest Score:</span>
                                <strong class="float-end text-success">{{ round($teamKPIs->max('composite_score'), 2) }}/100</strong>
                            </div>
                            <div class="list-group-item">
                                <span class="text-muted">Lowest Score:</span>
                                <strong class="float-end text-danger">{{ round($teamKPIs->min('composite_score'), 2) }}/100</strong>
                            </div>
                            <div class="list-group-item">
                                <span class="text-muted">Average Score:</span>
                                <strong class="float-end text-info">{{ round($teamKPIs->avg('composite_score'), 2) }}/100</strong>
                            </div>
                            <div class="list-group-item">
                                <span class="text-muted">Median Score:</span>
                                @php
                                    $scores = $teamKPIs->pluck('composite_score')->sort()->values();
                                    $count = $scores->count();
                                    $median = 0;
                                    if ($count > 0) {
                                        $median = $count % 2 === 0 
                                            ? ($scores[$count/2 - 1] + $scores[$count/2]) / 2 
                                            : $scores[floor($count/2)];
                                    }
                                @endphp
                                <strong class="float-end">{{ round($median, 2) }}/100</strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <a href="{{ route('reports.export-csv') }}?period={{ $period }}" class="btn btn-outline-success">
                    <i class="bi bi-download"></i> Export Team Data to CSV
                </a>
                <a href="{{ route('reports.monthly-recap') }}?period={{ $period }}" class="btn btn-outline-info">
                    <i class="bi bi-file-earmark-text"></i> View Monthly Recap
                </a>
            </div>
        </div>
        @endif
    </div>
</div>

<script>
    function changePeriod() {
        const period = document.getElementById('periodSelect').value;
        const supId = "{{ $selectedSupervisorId ?? 'all' }}";
        window.location.href = `{{ route('kpi.team') }}?period=${period}&supervisor_id=${supId}`;
    }
</script>

@if($canGenerate ?? false)
<!-- Modal Manage Team -->
<div class="modal fade" id="manageTeamModal" tabindex="-1" aria-labelledby="manageTeamModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content border-0 shadow-lg">
            <form action="{{ route('kpi.team.assign') }}" method="POST">
                @csrf
                <input type="hidden" name="period" value="{{ $period }}">
                
                <div class="modal-header bg-primary text-white py-3">
                    <h5 class="modal-title fw-bold text-white mb-0" id="manageTeamModalLabel">
                        <i class="bi bi-people-fill me-2"></i> Formasi Struktur Tim Karyawan
                    </h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body p-4">
                    <div class="alert alert-info border-0 mb-4" style="background-color: #e2e8f0; color: #0f172a !important;">
                        <i class="bi bi-info-circle-fill text-primary me-2"></i>
                        <span style="color: #0f172a !important;">Pilih <strong style="color: #0f172a !important;">Ketua Tim / Atasan (Supervisor)</strong> dan centang <strong style="color: #0f172a !important;">Anggota Tim</strong> di bawah ini untuk membentuk struktur kerja tim.</span>
                    </div>

                    <div class="mb-4">
                        <label class="form-label fw-bold text-dark" style="color: #0f172a !important;">Pilih Ketua Tim / Manager / Supervisor <span class="text-danger">*</span></label>
                        <select name="supervisor_id" id="modalSupervisorSelect" class="form-select form-control text-dark" style="color: #0f172a !important; font-weight: 600;" required onchange="onModalSupervisorChange()">
                            <option value="" disabled selected>-- Pilih Atasan / Ketua Tim --</option>
                            @foreach($allEmployees ?? [] as $emp)
                                <option value="{{ $emp->id }}" {{ ($selectedSupervisorId != 'all' && $selectedSupervisorId == $emp->id) ? 'selected' : '' }}>
                                    {{ $emp->fullname }} ({{ $emp->department->name ?? '-' }} - {{ $emp->position->name ?? ($emp->role->title ?? '-') }})
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="mb-3">
                        <div class="d-flex justify-content-between align-items-center mb-2">
                            <label class="form-label fw-bold text-dark mb-0" style="color: #0f172a !important;">Pilih Anggota Tim (Bawahan)</label>
                            <span class="text-muted small" style="color: #475569 !important;">Centang karyawan yang dipimpin oleh ketua tim ini</span>
                        </div>
                        
                        <div class="border rounded p-3 bg-light" style="max-height: 250px; overflow-y: auto; background-color: #f8fafc !important;">
                            @foreach($allEmployees ?? [] as $member)
                                <div class="form-check py-1 border-bottom border-light member-checkbox-item" data-sup-id="{{ $member->supervisor_id }}">
                                    <input class="form-check-input member-checkbox" type="checkbox" name="member_ids[]" value="{{ $member->id }}" id="member_{{ $member->id }}">
                                    <label class="form-check-label fw-bold ms-2" for="member_{{ $member->id }}" style="color: #0f172a !important;">
                                        {{ $member->fullname }}
                                        <small class="font-weight-normal ms-2" style="color: #475569 !important;">({{ $member->department->name ?? '-' }} • {{ $member->position->name ?? ($member->role->title ?? '-') }})</small>
                                    </label>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer bg-light px-4 py-3 justify-content-between">
                    <div>
                        <button type="button" class="btn btn-outline-danger rounded-pill px-3" id="btnDissolveTeam" onclick="dissolveSelectedTeam()" style="display: none;">
                            <i class="bi bi-trash-fill me-1"></i> Bubarkan / Hapus Tim Ini
                        </button>
                    </div>
                    <div>
                        <button type="button" class="btn btn-secondary rounded-pill px-4 me-2" data-bs-dismiss="modal">Batal</button>
                        <button type="submit" class="btn btn-primary rounded-pill px-4 shadow-sm">
                            <i class="bi bi-check-circle-fill me-1"></i> Simpan Formasi Tim
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function dissolveSelectedTeam() {
        const supSelect = document.getElementById('modalSupervisorSelect');
        const selectedSupId = supSelect.value;
        if (!selectedSupId) return;
        if (confirm('Apakah Anda yakin ingin membubarkan Tim ini? Seluruh anggota tim akan dilepas.')) {
            const checkboxes = document.querySelectorAll('.member-checkbox');
            checkboxes.forEach(cb => cb.checked = false);
            supSelect.form.submit();
        }
    }

    function onModalSupervisorChange() {
        const supSelect = document.getElementById('modalSupervisorSelect');
        const selectedSupId = supSelect.value;
        
        const dissolveBtn = document.getElementById('btnDissolveTeam');
        if (dissolveBtn) {
            dissolveBtn.style.display = selectedSupId ? 'inline-block' : 'none';
        }

        const items = document.querySelectorAll('.member-checkbox-item');
        items.forEach(item => {
            const currentSupId = item.getAttribute('data-sup-id');
            const checkbox = item.querySelector('.member-checkbox');
            
            if (checkbox.value == selectedSupId) {
                checkbox.checked = false;
                checkbox.disabled = true;
            } else {
                checkbox.disabled = false;
                if (currentSupId && currentSupId == selectedSupId) {
                    checkbox.checked = true;
                } else {
                    checkbox.checked = false;
                }
            }
        });
    }

    document.addEventListener("DOMContentLoaded", function() {
        if (document.getElementById('modalSupervisorSelect') && document.getElementById('modalSupervisorSelect').value) {
            onModalSupervisorChange();
        }
    });
</script>
@endif
@endsection
