<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use App\Models\Employee;
use App\Models\Presence;
use App\Models\Task;
use App\Models\Letter;
use App\Models\WorkLog;
use App\Models\FinancialTransaction;
use App\Models\Role;
use Carbon\Carbon;
use App\Services\KPICalculationService;

class FinanceRoleKPITest extends TestCase
{
    use RefreshDatabase;

    protected $employee;
    protected $service;

    protected function setUp(): void
    {
        parent::setUp();
        
        $this->seed(); // Seed master data
        
        // Find or create an employee with 'Finance' role
        $role = Role::where('title', 'Finance')->first();
        if (!$role) {
            $role = Role::create(['title' => 'Finance', 'description' => 'Finance Operator']);
        }
        
        // Assuming user seeder already created users and employees
        $this->employee = Employee::first();
        $this->employee->role_id = $role->id;
        $this->employee->save();
        
        // Clean up any existing records generated by seeder for this employee
        Presence::where('employee_id', $this->employee->id)->delete();
        WorkLog::where('employee_id', $this->employee->id)->delete();
        Task::where('assigned_to', $this->employee->id)->delete();
        Letter::where('user_id', $this->employee->user->id)->delete();
        FinancialTransaction::where('created_by', $this->employee->user->id)->delete();
        
        $this->service = new KPICalculationService($this->employee, Carbon::now()->subMonth()->format('Y-m'));
    }

    public function test_finance_role_gets_all_expected_kpis()
    {
        $today = Carbon::now()->subMonth();
        $periodStart = $today->copy()->startOfMonth();
        
        // 1. Mock Presence (For Checkout & Check-in WFO)
        Presence::create([
            'employee_id' => $this->employee->id,
            'work_type' => 'WFO',
            'status' => 'present',
            'is_late' => false,
            'date' => $periodStart->copy()->addDays(2)->format('Y-m-d'),
            'check_in' => $periodStart->copy()->addDays(2)->setHour(8)->format('Y-m-d H:i:s'),
            'check_out' => $periodStart->copy()->addDays(2)->setHour(17)->format('Y-m-d H:i:s')
        ]);
        
        // 2. Mock WorkLog
        WorkLog::create([
            'employee_id' => $this->employee->id,
            'title' => 'Daily Report',
            'description' => 'Did some finance stuff',
            'log_date' => $periodStart->copy()->addDays(2)->format('Y-m-d')
        ]);
        
        // 3. Mock Task
        Task::create([
            'assigned_to' => $this->employee->id,
            'title' => 'Financial Report',
            'status' => 'completed',
            'due_date' => $periodStart->copy()->addDays(3)->format('Y-m-d H:i:s')
        ]);
        
        // 4. Mock Letter
        Letter::create([
            'user_id' => $this->employee->user->id,
            'subject' => 'Invoice Letter',
            'letter_number' => 'INV-001',
            'content' => 'Please pay this invoice soon.',
            'status' => 'approved',
            'created_date' => $periodStart->copy()->addDays(2)->format('Y-m-d')
        ]);
        
        // 5. Mock Cashbook (FinancialTransaction)
        $account = \App\Models\FinancialAccount::first() ?? \App\Models\FinancialAccount::create(['name' => 'Main Account', 'balance' => 0]);
        
        FinancialTransaction::create([
            'account_id' => $account->id,
            'created_by' => $this->employee->user->id,
            'transaction_date' => $periodStart->copy()->addDays(2)->format('Y-m-d'),
            'description' => 'Income for today',
            'amount' => 50000,
            'type' => 'income',
            'created_at' => $periodStart->copy()->addDays(2)->setHour(10)->format('Y-m-d H:i:s') // SLA on time
        ]);
        
        // Inject configuration that mimics the Master KPI Config
        $config = [
            ['key' => 'presence', 'label' => 'Presensi (Checkout)', 'weight' => 10, 'applicable_roles' => ['*']],
            ['key' => 'worklog', 'label' => 'Log Kerja Harian', 'weight' => 15, 'applicable_roles' => ['*']],
            ['key' => 'task', 'label' => 'Penyelesaian Tugas', 'weight' => 15, 'applicable_roles' => ['*']],
            ['key' => 'sales', 'label' => 'Target Sales / Deal', 'weight' => 20, 'applicable_roles' => ['sales marketing']], // Should be N/A for Finance
            ['key' => 'letter', 'label' => 'Pengelolaan Surat', 'weight' => 10, 'applicable_roles' => ['*']],
            ['key' => 'cashbook', 'label' => 'Buku Kas / Cashbook', 'weight' => 15, 'applicable_roles' => ['finance']],
            ['key' => 'checkin_wfo', 'label' => 'Check-in (WFO)', 'weight' => 15, 'applicable_roles' => ['*']],
        ];

        // Execute Calculation
        $results = KPICalculationService::calculateDynamicMetricsForEmployee($this->employee, $today->format('Y-m'), $config);
        
        $activeDetails = $results['details'];
        $activeKeys = array_keys($activeDetails);

        // Assertions
        $this->assertContains('presence', $activeKeys);
        $this->assertContains('worklog', $activeKeys);
        $this->assertContains('task', $activeKeys);
        $this->assertContains('letter', $activeKeys);
        $this->assertContains('cashbook', $activeKeys);
        $this->assertContains('checkin_wfo', $activeKeys);
        
        // Ensure Sales is completely skipped (invisible)
        $this->assertArrayNotHasKey('sales', $activeDetails);
        
        // Ensure none of the Finance applicable metrics are flagged as N/A (because we seeded data for all of them)
        foreach (['presence', 'worklog', 'task', 'letter', 'cashbook', 'checkin_wfo'] as $key) {
            $this->assertFalse($activeDetails[$key]['is_na'] ?? true, "Indicator {$key} should not be N/A");
            $this->assertGreaterThan(0, $activeDetails[$key]['rate'], "Indicator {$key} should have a positive rate");
        }
    }

    public function test_finance_role_gets_na_when_no_data()
    {
        $today = Carbon::now()->subMonth();
        
        // We do NOT mock anything (0 Tasks, 0 Letters, 0 Cashbook, 0 Presences, 0 WorkLogs)
        
        $config = [
            ['key' => 'task', 'label' => 'Penyelesaian Tugas', 'weight' => 15, 'applicable_roles' => ['*']],
            ['key' => 'letter', 'label' => 'Pengelolaan Surat', 'weight' => 10, 'applicable_roles' => ['*']],
            ['key' => 'cashbook', 'label' => 'Buku Kas / Cashbook', 'weight' => 15, 'applicable_roles' => ['finance']],
        ];

        $results = KPICalculationService::calculateDynamicMetricsForEmployee($this->employee, $today->format('Y-m'), $config);
        $activeDetails = $results['details'];
        
        // Because all of them are N/A, total active weight is 0, which triggers the early return
        // We should assert that details is either empty or contains the indicators with actual_weight = 0
        // Currently the system returns early with empty details
        $this->assertEmpty($activeDetails);
    }
}
