@extends('layouts.dashboard')

@push('styles')
<style>
    /* High-contrast KPI Score & Performance Styling */
    .kpi-score-badge {
        font-weight: 700 !important;
        font-size: 0.9rem !important;
        padding: 6px 12px !important;
        border-radius: 6px !important;
        display: inline-block !important;
        box-shadow: 0 1px 3px rgba(0,0,0,0.12) !important;
    }
    
    .score-excellent {
        background-color: #059669 !important;
        color: #ffffff !important;
    }
    .score-good {
        background-color: #0284c7 !important;
        color: #ffffff !important;
    }
    .score-satisfactory {
        background-color: #d97706 !important;
        color: #ffffff !important;
    }
    .score-unsatisfactory {
        background-color: #dc2626 !important;
        color: #ffffff !important;
    }

    /* Table Contrast Improvements */
    .table td, .table th {
        vertical-align: middle !important;
        color: #1e293b !important;
    }
    .table th {
        font-weight: 700 !important;
        background-color: #f8fafc !important;
        color: #334155 !important;
    }

    /* Dark Mode Compatibility */
    [data-bs-theme="dark"] .table td,
    [data-bs-theme="dark"] .table th {
        color: #f1f5f9 !important;
    }
    [data-bs-theme="dark"] .table th {
        background-color: #1e293b !important;
    }
</style>
@endpush

@section('content')

<div class="page-heading">
    <div class="row align-items-center mb-3">
        <div class="col-md-6">
            <h3 class="fw-bold text-dark mb-1">Executive KPI Dashboard</h3>
            <p class="text-muted mb-0">Period: {{ \Carbon\Carbon::createFromFormat('Y-m', $period)->format('F Y') }}</p>
        </div>
        <div class="col-md-6 text-right">
            <div class="d-flex justify-content-end align-items-center flex-wrap gap-2">
                <form method="GET" class="form-inline d-flex align-items-center me-2">
                    <label class="me-2 fw-bold text-dark mb-0">Period: </label>
                    <input type="month" name="period" value="{{ $period }}" class="form-control" onchange="this.form.submit()">
                </form>

                @if($canGenerate ?? false)
                <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                    @csrf
                    <input type="hidden" name="period" value="{{ $period }}">
                    <button type="submit" class="btn btn-primary btn-md shadow-sm">
                        <i class="bi bi-play-circle-fill me-1"></i> {{ ($isGenerated ?? false) ? 'Recalculate KPI' : 'Generate KPI Periode Ini' }}
                    </button>
                </form>
                @endif
            </div>
        </div>
    </div>
</div>

<div class="page-content">
    <div class="container-fluid px-0">
        @if(session('success'))
            <div class="alert alert-success alert-dismissible fade show border-0 shadow-sm mb-4" role="alert">
                <i class="bi bi-check-circle-fill me-2"></i> {{ session('success') }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        @endif

        @if(!($isGenerated ?? true))
            <!-- Empty State Card when KPI has not been generated by HR -->
            <div class="card border-0 shadow-sm my-4">
                <div class="card-body text-center py-5">
                    <div class="mb-3">
                        <i class="bi bi-calendar-x text-warning display-4"></i>
                    </div>
                    <h4 class="fw-bold text-dark">KPI Belum Digenerate untuk Periode {{ \Carbon\Carbon::createFromFormat('Y-m', $period)->format('F Y') }}</h4>
                    <p class="text-muted max-w-lg mx-auto mb-4">
                        Laporan KPI pada periode ini belum diterbitkan oleh HR / Master Admin. <br>
                        Penilaian dihitung berdasarkan <strong>Kepatuhan Checkout Presensi</strong> dan <strong>Pengisian Log Kerja Harian</strong>.
                    </p>
                    @if($canGenerate ?? false)
                        <form action="{{ route('reports.generate-kpi') }}" method="POST" class="d-inline">
                            @csrf
                            <input type="hidden" name="period" value="{{ $period }}">
                            <button type="submit" class="btn btn-primary btn-lg px-4 shadow">
                                <i class="bi bi-play-circle-fill me-2"></i> Generate KPI Periode Ini Sekarang
                            </button>
                        </form>
                    @else
                        <span class="badge bg-secondary px-3 py-2 fs-6">Menunggu HR Administrator memproses KPI bulan ini</span>
                    @endif
                </div>
            </div>
        @else
        <!-- Key Metrics -->
        <div class="row mb-4">
            <div class="col-12 col-sm-6 col-md-3 mb-3">
                <div class="card border-0 shadow-sm border-left-primary h-100">
                    <div class="card-body">
                        <h6 class="text-primary font-weight-bold mb-1">Total Employees</h6>
                        <h2 class="mb-0 fw-bold text-dark">{{ $totalEmployees }}</h2>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-3 mb-3">
                <div class="card border-0 shadow-sm border-left-success h-100">
                    <div class="card-body">
                        <h6 class="text-success font-weight-bold mb-1">Excellent</h6>
                        <h2 class="mb-0 fw-bold text-dark">{{ $excellentCount }}<span class="text-sm"> / {{ $totalEmployees }}</span></h2>
                        <small class="text-muted">{{ $totalEmployees > 0 ? round(($excellentCount / $totalEmployees) * 100, 1) : 0 }}%</small>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-3 mb-3">
                <div class="card border-0 shadow-sm border-left-info h-100">
                    <div class="card-body">
                        <h6 class="text-info font-weight-bold mb-1">Good Performance</h6>
                        <h2 class="mb-0 fw-bold text-dark">{{ $goodCount }}<span class="text-sm"> / {{ $totalEmployees }}</span></h2>
                        <small class="text-muted">{{ $totalEmployees > 0 ? round(($goodCount / $totalEmployees) * 100, 1) : 0 }}%</small>
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6 col-md-3 mb-3">
                <div class="card border-0 shadow-sm border-left-danger h-100">
                    <div class="card-body">
                        <h6 class="text-danger font-weight-bold mb-1">Unresolved Incidents</h6>
                        <h2 class="mb-0 fw-bold text-dark">{{ $recentIncidents->count() }}</h2>
                        <small class="text-muted">Require Attention</small>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <!-- Top Performers -->
            <div class="col-12 col-md-6 mb-3">
                <div class="card border-0 shadow-sm">
                    <div class="card-header bg-success text-white py-3">
                        <h5 class="mb-0 fw-bold"><i class="bi bi-star-fill me-2"></i>Top 5 Performers</h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            @forelse($topPerformers as $index => $record)
                            <div class="list-group-item border-0 border-bottom py-3">
                                <div class="d-flex w-100 justify-content-between align-items-center">
                                    <div>
                                        <h6 class="mb-1 fw-bold text-dark">
                                            {{ $index + 1 }}. {{ $record->employee?->fullname ?? 'Unknown' }}
                                        </h6>
                                        <small class="text-muted">{{ $record->employee?->department?->name ?? 'Unknown' }} • {{ $record->employee?->role?->title ?? 'Unknown' }}</small>
                                    </div>
                                    <span class="badge bg-success text-white px-3 py-2 fs-6 fw-bold shadow-sm" style="height: fit-content;">{{ round($record->composite_score, 2) }}</span>
                                </div>
                                <div class="progress" style="height: 6px; margin-top: 10px;">
                                    <div class="progress-bar bg-success" style="width: {{ $record->composite_score }}%;"></div>
                                </div>
                            </div>
                            @empty
                            <p class="text-muted text-center py-3">No data available</p>
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>

            <!-- Bottom Performers -->
            <div class="col-12 col-md-6 mb-3">
                <div class="card border-0 shadow-sm">
                    <div class="card-header bg-warning text-dark py-3">
                        <h5 class="mb-0 fw-bold"><i class="bi bi-exclamation-triangle-fill me-2"></i>Bottom 5 Performers (Development Focus)</h5>
                    </div>
                    <div class="card-body">
                        <div class="list-group">
                            @forelse($bottomPerformers as $index => $record)
                            <div class="list-group-item border-0 border-bottom py-3">
                                <div class="d-flex w-100 justify-content-between align-items-center">
                                    <div>
                                        <h6 class="mb-1 fw-bold text-dark">
                                            {{ $index + 1 }}. {{ $record->employee?->fullname ?? 'Unknown' }}
                                        </h6>
                                        <small class="text-muted">{{ $record->employee?->department?->name ?? 'Unknown' }} • {{ $record->employee?->role?->title ?? 'Unknown' }}</small>
                                    </div>
                                    <span class="badge bg-danger text-white px-3 py-2 fs-6 fw-bold shadow-sm" style="height: fit-content;">{{ round($record->composite_score, 2) }}</span>
                                </div>
                                <div class="progress" style="height: 6px; margin-top: 10px;">
                                    <div class="progress-bar bg-danger" style="width: {{ $record->composite_score }}%;"></div>
                                </div>
                            </div>
                            @empty
                            <p class="text-muted text-center py-3">No data available</p>
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Department Performance -->
        <div class="row mt-4">
            <div class="col-12 mb-3">
                <div class="card border-0 shadow-sm">
                    <div class="card-header bg-white py-3">
                        <h5 class="card-title mb-0 fw-bold text-dark"><i class="bi bi-building me-2 text-primary"></i>Department Performance Comparison</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover align-middle mb-0">
                                <thead>
                                    <tr>
                                        <th>Department</th>
                                        <th>Employees</th>
                                        <th>Avg Score</th>
                                        <th>Score Distribution</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse($departments as $dept)
                                    <tr>
                                        <td><strong class="text-dark fs-6">{{ $dept['name'] }}</strong></td>
                                        <td><span class="badge bg-secondary text-white px-2 py-1">{{ $dept['employee_count'] }}</span></td>
                                        <td>
                                            @php
                                                $scoreClass = $dept['avg_score'] >= 90 ? 'score-excellent' : 
                                                            ($dept['avg_score'] >= 75 ? 'score-good' : 
                                                            ($dept['avg_score'] >= 60 ? 'score-satisfactory' : 'score-unsatisfactory'));
                                            @endphp
                                            <span class="kpi-score-badge {{ $scoreClass }}">
                                                {{ round($dept['avg_score'], 2) }}/100
                                            </span>
                                        </td>
                                        <td>
                                            <div class="progress" style="height: 22px; border-radius: 6px;">
                                                <div class="progress-bar {{ 
                                                    $dept['avg_score'] >= 90 ? 'bg-success' : 
                                                    ($dept['avg_score'] >= 75 ? 'bg-info' : 
                                                    ($dept['avg_score'] >= 60 ? 'bg-warning text-dark' : 'bg-danger'))
                                                }} font-weight-bold" 
                                                     style="width: {{ min($dept['avg_score'], 100) }}%;">
                                                    {{ round($dept['avg_score'], 1) }}%
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td colspan="4" class="text-center text-muted py-3">No data available</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Recent Incidents -->
        @if($recentIncidents->count() > 0)
        <div class="row mt-4">
            <div class="col-12 mb-3">
                <div class="card border-0 shadow-sm">
                    <div class="card-header bg-danger text-white py-3">
                        <h5 class="card-title mb-0 fw-bold"><i class="bi bi-shield-exclamation me-2"></i>Unresolved Incidents</h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover align-middle mb-0">
                                <thead>
                                    <tr>
                                        <th>Employee</th>
                                        <th>Type</th>
                                        <th>Date</th>
                                        <th>Severity</th>
                                        <th>Status</th>
                                        <th>Description</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($recentIncidents as $incident)
                                    <tr>
                                        <td><strong class="text-dark">{{ $incident->employee?->fullname ?? 'Unknown' }}</strong></td>
                                        <td>{{ ucfirst(str_replace('_', ' ', $incident->type)) }}</td>
                                        <td>{{ $incident->incident_date->format('d M Y') }}</td>
                                        <td>
                                            @switch($incident->severity)
                                                @case('low')
                                                    <span class="badge bg-info text-white px-2 py-1">Low</span>
                                                    @break
                                                @case('medium')
                                                    <span class="badge bg-warning text-dark px-2 py-1">Medium</span>
                                                    @break
                                                @case('high')
                                                    <span class="badge bg-danger text-white px-2 py-1">High</span>
                                                    @break
                                                @default
                                                    <span class="badge bg-dark text-white px-2 py-1">Critical</span>
                                            @endswitch
                                        </td>
                                        <td>
                                            <span class="badge bg-{{ $incident->status === 'resolved' ? 'success' : 'warning' }} {{ $incident->status === 'resolved' ? 'text-white' : 'text-dark' }} px-2 py-1">
                                                {{ ucfirst($incident->status) }}
                                            </span>
                                        </td>
                                        <td><small class="text-muted">{{ Str::limit($incident->description, 50) }}</small></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endif

        <!-- Export Actions -->
        <div class="row mt-4">
            <div class="col-12 mb-3">
                <a href="{{ route('reports.monthly-recap') }}?period={{ $period }}" class="btn btn-info text-white me-2 shadow-sm">
                    <i class="bi bi-list-ul me-1"></i> View Monthly Recap
                </a>
                <a href="{{ route('reports.export-csv') }}?period={{ $period }}" class="btn btn-success shadow-sm">
                    <i class="bi bi-download me-1"></i> Export All Data to CSV
                </a>
            </div>
        </div>
        @endif
    </div>
</div>
@endsection

