<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\EmployeeKPIRecord;
use App\Models\KPI;
use App\Models\PerformanceReview;
use App\Models\Incident;
use App\Models\LetterConfiguration;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
use Barryvdh\DomPDF\Facade\Pdf;

class ReportingController extends Controller
{
    /**
     * Monthly Performance Recap
    /**
     * Generate Monthly KPI for all employees (Manual HR Trigger)
     */
    public function generateMonthlyKPI(Request $request)
    {
        $user = Auth::user();
        $roleTitle = $user->employee?->role->title ?? null;

        if (!in_array($roleTitle, ['HR Administrator', \App\Constants\Roles::MASTER_ADMIN])) {
            abort(403, 'Hanya HR Administrator atau Master Admin yang dapat melakukan Generate KPI.');
        }

        $period = $request->input('period', now()->format('Y-m'));
        $employees = Employee::all();

        if ($employees->isEmpty()) {
            return redirect()->back()->with('error', 'Tidak ada data karyawan untuk digenerate.');
        }

        // Get or create standard KPI master record for 2-metric KPI
        $kpi = KPI::firstOrCreate(
            ['code' => 'KPI_DUAL_METRIC'],
            [
                'name' => 'Attendance Checkout & Work Log Metric',
                'category' => 'Productivity & Attendance',
                'target_value' => 100,
                'weight' => 1.0,
                'unit' => '%',
                'status' => 'active',
            ]
        );

        // Remove old legacy records for this period to ensure clean 2-metric generation
        EmployeeKPIRecord::where('period', $period)->delete();

        $generatedCount = 0;
        $results = [];
        foreach ($employees as $emp) {
            $dual = \App\Services\KPICalculationService::calculateDualMetricsForEmployee($emp, $period);
            
            // Upsert record for this employee and period
            EmployeeKPIRecord::updateOrCreate(
                [
                    'employee_id' => $emp->id,
                    'kpi_id' => $kpi->id,
                    'period' => $period,
                ],
                [
                    'actual_value' => $dual['score'],
                    'target_value' => 100,
                    'composite_score' => $dual['score'],
                    'status' => $dual['score'] >= 75 ? 'achieved' : ($dual['score'] >= 60 ? 'warning' : 'critical'),
                    'performance_level' => $dual['level'],
                    'notes' => "Generated by HR (Checkout: {$dual['checkout_pct']}%, WorkLog: {$dual['log_pct']}%)",
                    'updated_at' => now(),
                ]
            );

            $results[] = [
                'employee_id' => $emp->id,
                'fullname' => $emp->fullname,
                'department' => $emp->department ? $emp->department->name : '-',
                'position' => $emp->position ? $emp->position->name : ($emp->role ? $emp->role->title : '-'),
                'working_days' => $dual['working_days'] ?? 20,
                'log_count' => $dual['unique_log_days'] ?? 0,
                'log_percentage' => $dual['log_pct'],
                'checkout_percentage' => $dual['checkout_pct'],
                'composite_score' => $dual['score'],
                'performance_level' => $dual['level'],
                'photo' => $emp->profile_photo ?? null,
                'photo_url' => $emp->profile_photo ? asset('storage/' . $emp->profile_photo) : null,
            ];

            $generatedCount++;
        }

        // Sort data descending by composite score to determine ranking and Employee of the Month
        $sortedData = collect($results)
            ->sortByDesc('composite_score')
            ->values()
            ->all();

        $cacheData = [
            'period' => $period,
            'last_updated' => now()->toDateTimeString(),
            'data' => $sortedData,
            'best_employee' => $sortedData[0] ?? null,
        ];

        \Illuminate\Support\Facades\Cache::put('company_kpi_dashboard_data', $cacheData, 86400 * 30);

        return redirect()->back()->with('success', "KPI Periode {$period} berhasil digenerate untuk {$generatedCount} karyawan!");
    }

    /**
     * Monthly Performance Recap
     */
    public function monthlyRecap()
    {
        $user = Auth::user();
        $roleTitle = $user->employee?->role->title ?? null;
        $period = request('period', now()->format('Y-m'));
        $department = $user->employee?->department;

        // Access: Manager / Unit Head/HR Administrator/Master Admin see broader data; other roles see diri sendiri
        if (!in_array($roleTitle, ['Manager / Unit Head', 'HR Administrator', \App\Constants\Roles::MASTER_ADMIN])) {
            if (!$user->employee) {
                abort(403, 'Unauthorized access');
            }
            $employees = collect([$user->employee]);
        } else {
            // Get employees (department-based for managers, all for HR Administrator/Master Admin)
            if ($roleTitle === 'Manager / Unit Head') {
                $employees = Employee::where('department_id', $department->id ?? 0)->get();
            } else {
                $employees = Employee::all();
            }
        }

        // Check if records have been generated by HR for this period
        $employeeIds = $employees->pluck('id');
        $allRecords = EmployeeKPIRecord::whereIn('employee_id', $employeeIds)
            ->where('period', $period)
            ->get()
            ->groupBy('employee_id');

        $isGenerated = EmployeeKPIRecord::where('period', $period)->exists();

        $kpiData = [];
        if ($isGenerated) {
            foreach ($employees as $emp) {
                $records = $allRecords->get($emp->id, collect());

                if ($records->count() > 0) {
                    $summary = \App\Services\KPICalculationService::calculateWeightedScore($records);
                    
                    $kpiData[] = [
                        'employee' => $emp,
                        'composite_score' => $summary['score'],
                        'performance_level' => $summary['level'],
                        'achievements' => $records->where('status', 'achieved')->count(),
                        'warnings' => $records->where('status', 'warning')->count(),
                        'critical' => $records->where('status', 'critical')->count(),
                    ];
                }
            }

            // Sort by composite score
            usort($kpiData, function($a, $b) {
                return $b['composite_score'] <=> $a['composite_score'];
            });
        }

        $canGenerate = in_array($roleTitle, ['HR Administrator', \App\Constants\Roles::MASTER_ADMIN]);

        return view('reports.monthly-recap', compact('period', 'kpiData', 'isGenerated', 'canGenerate'));
    }

    /**
     * Executive Dashboard
     */
    public function executiveDashboard()
    {
        $user = Auth::user();
        $roleTitle = $user->employee?->role->title ?? null;

        if (!in_array($roleTitle, ['HR Administrator', \App\Constants\Roles::MASTER_ADMIN])) {
            abort(403, 'Only HR Administrator or Master Admin can access executive dashboard');
        }

        $period = request('period', now()->format('Y-m'));
        $departmentFilter = request('department_id');
        $roleFilter = request('role_id');

        // Check if KPI records have been generated by HR for this period
        $isGenerated = EmployeeKPIRecord::where('period', $period)->exists();

        // Get all relevant employees first
        $employeeQuery = Employee::query();
        if ($departmentFilter) {
            $employeeQuery->where('department_id', $departmentFilter);
        }
        if ($roleFilter) {
            $employeeQuery->where('role_id', $roleFilter);
        }
        $employees = $employeeQuery->get();

        // Get all records for these employees in this period
        $allRecords = EmployeeKPIRecord::with('kpi')
            ->whereIn('employee_id', $employees->pluck('id'))
            ->where('period', $period)
            ->get()
            ->groupBy('employee_id');

        // Calculate weighted scores for each employee
        $performanceData = $employees->map(function($emp) use ($allRecords) {
            $records = $allRecords->get($emp->id, collect());
            if ($records->isEmpty()) {
                return null;
            }
            $summary = \App\Services\KPICalculationService::calculateWeightedScore($records);
            return (object) [
                'employee' => $emp,
                'composite_score' => $summary['score'],
                'performance_level' => $summary['level'],
            ];
        })->filter()->sortByDesc('composite_score');

        // Top performers
        $topPerformers = $performanceData->take(5);

        // Bottom performers
        $bottomPerformers = $performanceData->reverse()->take(5);

        // Department averages
        $departments = [];
        $allDepartments = \App\Models\Department::has('employees')->get();
        
        foreach ($allDepartments as $dept) {
            $deptEmployees = $dept->employees;
            $deptScores = $performanceData->whereIn('employee.id', $deptEmployees->pluck('id'));
            
            if ($deptScores->isEmpty()) {
                continue;
            }
            
            $departments[] = [
                'name' => $dept->name,
                'avg_score' => round($deptScores->avg('composite_score'), 2),
                'employee_count' => $deptScores->count(),
            ];
        }

        // Overall statistics
        $totalEmployees = Employee::count();
        $excellentCount = $performanceData->where('performance_level', 'excellent')->count();
        $goodCount = $performanceData->where('performance_level', 'good')->count();

        // Recent incidents
        $recentIncidents = Incident::where('status', '!=', 'resolved')
            ->orderByDesc('incident_date')
            ->limit(5)
            ->with('employee')
            ->get();

        // Pass departments and roles for filter dropdowns
        $allDepartments = \App\Models\Department::orderBy('name')->get();
        $allRoles = \App\Models\Role::orderBy('title')->get();
        $canGenerate = true;

        return view('reports.executive-dashboard', compact(
            'period',
            'topPerformers',
            'bottomPerformers',
            'departments',
            'totalEmployees',
            'excellentCount',
            'goodCount',
            'recentIncidents',
            'allDepartments',
            'allRoles',
            'departmentFilter',
            'roleFilter',
            'isGenerated',
            'canGenerate'
        ));
    }


    /**
     * Export KPI Report to PDF
     */
    public function exportPDF($id)
    {
        $user = Auth::user();
        $employee = Employee::with(['department', 'role', 'supervisor'])->findOrFail($id);
        $config = LetterConfiguration::first() ?: new LetterConfiguration([
            'company_name' => 'ARATECHNOLOGY',
            'company_address' => 'Jakarta, Indonesia',
        ]);

        if ($user->id !== $employee->user_id && !in_array($user->employee?->role->title ?? null, ['HR Administrator', \App\Constants\Roles::MASTER_ADMIN, 'Manager / Unit Head'])) {
            abort(403, 'Unauthorized');
        }

        $period = request('period', now()->format('Y-m'));
        $records = EmployeeKPIRecord::with('kpi')
            ->where('employee_id', $employee->id)
            ->where('period', $period)
            ->get();

        // Calculate summary using service (it handles empty records by returning 0/Unsatisfactory)
        $summary = \App\Services\KPICalculationService::calculateWeightedScore($records);
        
        $record = (object) [
            'employee' => $employee,
            'period' => $period,
            'composite_score' => $summary['score'],
            'performance_level' => $summary['level'],
            'created_at' => now(),
        ];
        
        // Group records by category for the report breakdown
        $kpisByCategory = $records->groupBy(function($r) {
            return $r->kpi->category ?? 'General';
        });
        
        // Calculate category scores for the breakdown table
        $categoryBreakdown = [];
        foreach ($kpisByCategory as $category => $items) {
            $totalAchievement = 0;
            foreach ($items as $item) {
                $totalAchievement += $item->getAchievementPercentage();
            }
            $avg = $items->count() > 0 ? $totalAchievement / $items->count() : 0;
            
            $categoryBreakdown[] = [
                'name' => $category,
                'score' => $avg,
                'count' => $items->count()
            ];
        }

        $incidents = Incident::where('employee_id', $employee->id)
            ->whereYear('incident_date', substr($period, 0, 4))
            ->whereMonth('incident_date', substr($period, 5, 2))
            ->orderByDesc('incident_date')
            ->get();

        $pdf = Pdf::loadView('reports/kpi-pdf', compact('record', 'records', 'kpisByCategory', 'categoryBreakdown', 'incidents', 'config'))
                  ->setPaper('a4', 'portrait')
                  ->setOption('margin-top', 0)
                  ->setOption('margin-bottom', 0);

        return $pdf->download('KPI_Report_' . str_replace(' ', '_', $employee->fullname) . '_' . $period . '.pdf');
    }

    /**
     * Export Monthly Recap to CSV
     */
    public function exportCSV()
    {
        $user = Auth::user();
        $employee = $user->employee;

        if (!$employee) {
            abort(403, 'User not linked to employee.');
        }

        $roleTitle = $employee->role->title ?? null;
        $period = request('period', now()->format('Y-m'));
        
        // Define data visibility based on role using Eloquent
        if (in_array($roleTitle, ['HR Administrator', \App\Constants\Roles::MASTER_ADMIN])) {
            // HR Administrator/Master Admin see everything
            $records = EmployeeKPIRecord::with(['employee.department', 'kpi'])
                ->where('period', $period)
                ->orderBy('employee_id')
                ->orderBy('kpi_id')
                ->get();
        } elseif ($roleTitle === 'Manager / Unit Head') {
            // Manager / Unit Head see their department
            $records = EmployeeKPIRecord::with(['employee.department', 'kpi'])
                ->whereHas('employee', function($q) use ($employee) {
                    $q->where('department_id', $employee->department_id ?? 0);
                })
                ->where('period', $period)
                ->orderBy('employee_id')
                ->orderBy('kpi_id')
                ->get();
        } else {
            // Others only see their own
            $records = EmployeeKPIRecord::with(['employee.department', 'kpi'])
                ->where('employee_id', $employee->id)
                ->where('period', $period)
                ->orderBy('kpi_id')
                ->get();
        }

        $filename = 'KPI_Report_' . str_replace(' ', '_', $roleTitle) . '_' . $period . '.csv';
        $handle = fopen('php://memory', 'r+');

        // Header
        fputcsv($handle, [
            'Employee',
            'Department',
            'KPI',
            'Actual Value',
            'Target Value',
            'Status',
            'Performance Level',
            'Period'
        ]);

        // Data
        foreach ($records as $record) {
            fputcsv($handle, [
                $record->employee->fullname ?? 'N/A',
                $record->employee->department?->name ?? 'N/A',
                $record->kpi->name ?? 'N/A',
                $record->actual_value,
                $record->target_value,
                $record->status,
                $record->performance_level,
                $record->period
            ]);
        }

        rewind($handle);
        $csv = stream_get_contents($handle);
        fclose($handle);

        return response($csv, 200, [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }
}
