name: Deploy Corevo

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to CloudPanel
    runs-on: ubuntu-latest

    steps:
      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/htdocs/corevo.aratechnology.id

            echo "-- Pulling the new code"
            git pull origin main

            echo "-- Update PHP Vendor"
            composer install --no-dev --optimize-autoloader

            echo "-- Update Database"
            php artisan migrate --force

            echo "-- Clean Server Cache"
            php artisan optimize:clear

            echo "-- Restart Queue Workers"
            php artisan queue:restart

            echo "Deploy Completed"
